// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum } from './runtime';

export class AABB extends ApiObject {
    getCenterX(): number {
        return callNum(0, this.handle, []);
    }

    getCenterY(): number {
        return callNum(1, this.handle, []);
    }

    getCenterZ(): number {
        return callNum(2, this.handle, []);
    }

    getExtremeX(): number {
        return callNum(3, this.handle, []);
    }

    getExtremeY(): number {
        return callNum(4, this.handle, []);
    }

    getExtremeZ(): number {
        return callNum(5, this.handle, []);
    }

}
