// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callStrArg, callVoid, wrap } from './runtime';
import { IterableHashTable } from './IterableHashTable';
import { LocalPoint } from './LocalPoint';
import { Model } from './Model';
import { Node } from './Node';
import { Point } from './Point';
import { WorldArea } from './WorldArea';
import { WorldPoint } from './WorldPoint';
import { WorldView } from './WorldView';

export class Actor extends ApiObject {
    clearSpotAnims(): void {
        callVoid(6, this.handle, []);
    }

    createSpotAnim(a0: number, a1: number, a2: number, a3: number): void {
        callVoid(7, this.handle, [a0, a1, a2, a3]);
    }

    getAnimation(): number {
        return callNum(8, this.handle, []);
    }

    getAnimationFrame(): number {
        return callNum(9, this.handle, []);
    }

    getAnimationHeightOffset(): number {
        return callNum(10, this.handle, []);
    }

    getCameraFocus(): LocalPoint | null {
        return wrap(11, this.handle, [], LocalPoint);
    }

    getCanvasSpriteLocation(a0: ApiObject | null, a1: number): Point | null {
        return wrap(12, this.handle, [(a0 ? a0.handle : -1), a1], Point);
    }

    getCombatLevel(): number {
        return callNum(13, this.handle, []);
    }

    getCurrentOrientation(): number {
        return callNum(14, this.handle, []);
    }

    getFootprintSize(): number {
        return callNum(15, this.handle, []);
    }

    getGraphic(): number {
        return callNum(16, this.handle, []);
    }

    getGraphicHeight(): number {
        return callNum(17, this.handle, []);
    }

    getHash(): number {
        return callNum(18, this.handle, []);
    }

    getHealthRatio(): number {
        return callNum(19, this.handle, []);
    }

    getHealthScale(): number {
        return callNum(20, this.handle, []);
    }

    getIdlePoseAnimation(): number {
        return callNum(21, this.handle, []);
    }

    getIdleRotateLeft(): number {
        return callNum(22, this.handle, []);
    }

    getIdleRotateRight(): number {
        return callNum(23, this.handle, []);
    }

    getInteracting(): Actor | null {
        return wrap(24, this.handle, [], Actor);
    }

    getLocalLocation(): LocalPoint | null {
        return wrap(25, this.handle, [], LocalPoint);
    }

    getLogicalHeight(): number {
        return callNum(26, this.handle, []);
    }

    getMinimapLocation(): Point | null {
        return wrap(27, this.handle, [], Point);
    }

    getModel(): Model | null {
        return wrap(28, this.handle, [], Model);
    }

    getModelHeight(): number {
        return callNum(29, this.handle, []);
    }

    getName(): string | null {
        return callStr(30, this.handle, []);
    }

    getNext(): Node | null {
        return wrap(31, this.handle, [], Node);
    }

    getOrientation(): number {
        return callNum(32, this.handle, []);
    }

    getOverheadCycle(): number {
        return callNum(33, this.handle, []);
    }

    getOverheadText(): string | null {
        return callStr(34, this.handle, []);
    }

    getPoseAnimation(): number {
        return callNum(35, this.handle, []);
    }

    getPoseAnimationFrame(): number {
        return callNum(36, this.handle, []);
    }

    getPrevious(): Node | null {
        return wrap(37, this.handle, [], Node);
    }

    getRenderMode(): number {
        return callNum(38, this.handle, []);
    }

    getRunAnimation(): number {
        return callNum(39, this.handle, []);
    }

    getSpotAnimFrame(): number {
        return callNum(40, this.handle, []);
    }

    getSpotAnims(): IterableHashTable | null {
        return wrap(41, this.handle, [], IterableHashTable);
    }

    getWalkAnimation(): number {
        return callNum(42, this.handle, []);
    }

    getWalkRotate180(): number {
        return callNum(43, this.handle, []);
    }

    getWalkRotateLeft(): number {
        return callNum(44, this.handle, []);
    }

    getWalkRotateRight(): number {
        return callNum(45, this.handle, []);
    }

    getWorldArea(): WorldArea | null {
        return wrap(46, this.handle, [], WorldArea);
    }

    getWorldLocation(): WorldPoint | null {
        return wrap(47, this.handle, [], WorldPoint);
    }

    getWorldView(): WorldView | null {
        return wrap(48, this.handle, [], WorldView);
    }

    hasSpotAnim(a0: number): boolean {
        return callNum(49, this.handle, [a0]) !== 0;
    }

    isDead(): boolean {
        return callNum(50, this.handle, []) !== 0;
    }

    isInteracting(): boolean {
        return callNum(51, this.handle, []) !== 0;
    }

    removeSpotAnim(a0: number): void {
        callVoid(52, this.handle, [a0]);
    }

    setActionFrame(a0: number): void {
        callVoid(53, this.handle, [a0]);
    }

    setAnimation(a0: number): void {
        callVoid(54, this.handle, [a0]);
    }

    setAnimationFrame(a0: number): void {
        callVoid(55, this.handle, [a0]);
    }

    setDead(a0: boolean): void {
        callVoid(56, this.handle, [(a0 ? 1 : 0)]);
    }

    setGraphic(a0: number): void {
        callVoid(57, this.handle, [a0]);
    }

    setGraphicHeight(a0: number): void {
        callVoid(58, this.handle, [a0]);
    }

    setIdlePoseAnimation(a0: number): void {
        callVoid(59, this.handle, [a0]);
    }

    setIdleRotateLeft(a0: number): void {
        callVoid(60, this.handle, [a0]);
    }

    setIdleRotateRight(a0: number): void {
        callVoid(61, this.handle, [a0]);
    }

    setModelHeight(a0: number): void {
        callVoid(62, this.handle, [a0]);
    }

    setOverheadCycle(a0: number): void {
        callVoid(63, this.handle, [a0]);
    }

    setOverheadText(a0: string): void {
        callStrArg(0, a0);
        callVoid(64, this.handle, [0]);
    }

    setPoseAnimation(a0: number): void {
        callVoid(65, this.handle, [a0]);
    }

    setPoseAnimationFrame(a0: number): void {
        callVoid(66, this.handle, [a0]);
    }

    setRunAnimation(a0: number): void {
        callVoid(67, this.handle, [a0]);
    }

    setSpotAnimFrame(a0: number): void {
        callVoid(68, this.handle, [a0]);
    }

    setWalkAnimation(a0: number): void {
        callVoid(69, this.handle, [a0]);
    }

    setWalkRotate180(a0: number): void {
        callVoid(70, this.handle, [a0]);
    }

    setWalkRotateLeft(a0: number): void {
        callVoid(71, this.handle, [a0]);
    }

    setWalkRotateRight(a0: number): void {
        callVoid(72, this.handle, [a0]);
    }

}
