// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Actor } from './Actor';

export class ActorDeath extends ApiObject {
    getActor(): Actor | null {
        return wrap(1603, this.handle, [], Actor);
    }

    hashCode(): number {
        return callNum(1604, this.handle, []);
    }

    toString(): string | null {
        return callStr(1605, this.handle, []);
    }

}
