// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callVoid, wrap } from './runtime';
import { Model } from './Model';
import { Node } from './Node';

export class ActorSpotAnim extends ApiObject {
    getAnimationHeightOffset(): number {
        return callNum(73, this.handle, []);
    }

    getCycle(): number {
        return callNum(74, this.handle, []);
    }

    getFrame(): number {
        return callNum(75, this.handle, []);
    }

    getHash(): number {
        return callNum(76, this.handle, []);
    }

    getHeight(): number {
        return callNum(77, this.handle, []);
    }

    getId(): number {
        return callNum(78, this.handle, []);
    }

    getModel(): Model | null {
        return wrap(79, this.handle, [], Model);
    }

    getModelHeight(): number {
        return callNum(80, this.handle, []);
    }

    getNext(): Node | null {
        return wrap(81, this.handle, [], Node);
    }

    getPrevious(): Node | null {
        return wrap(82, this.handle, [], Node);
    }

    getRenderMode(): number {
        return callNum(83, this.handle, []);
    }

    getStartCycle(): number {
        return callNum(84, this.handle, []);
    }

    setCycle(a0: number): void {
        callVoid(85, this.handle, [a0]);
    }

    setFrame(a0: number): void {
        callVoid(86, this.handle, [a0]);
    }

    setHeight(a0: number): void {
        callVoid(87, this.handle, [a0]);
    }

    setId(a0: number): void {
        callVoid(88, this.handle, [a0]);
    }

    setModelHeight(a0: number): void {
        callVoid(89, this.handle, [a0]);
    }

    setStartCycle(a0: number): void {
        callVoid(90, this.handle, [a0]);
    }

}
