// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { AmbientSoundEffect } from './AmbientSoundEffect';

export class AmbientSoundEffectCreated extends ApiObject {
    getAmbientSoundEffect(): AmbientSoundEffect | null {
        return wrap(1608, this.handle, [], AmbientSoundEffect);
    }

    hashCode(): number {
        return callNum(1609, this.handle, []);
    }

    toString(): string | null {
        return callStr(1610, this.handle, []);
    }

}
