// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum } from './runtime';

export class AmbientSoundEffect extends ApiObject {
    getBackgroundSoundEffectIds(): ApiArray<number> {
        return new ApiArray<number>(callNum(91, this.handle, []), 'num', null);
    }

    getPlane(): number {
        return callNum(92, this.handle, []);
    }

    getSoundEffectId(): number {
        return callNum(93, this.handle, []);
    }

}
