// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callVoid } from './runtime';

export class Animation extends ApiObject {
    getDuration(): number {
        return callNum(94, this.handle, []);
    }

    getFrameLengths(): ApiArray<number> {
        return new ApiArray<number>(callNum(95, this.handle, []), 'num', null);
    }

    getFrameStep(): number {
        return callNum(96, this.handle, []);
    }

    getId(): number {
        return callNum(97, this.handle, []);
    }

    getLeftHandItem(): number {
        return callNum(98, this.handle, []);
    }

    getNumFrames(): number {
        return callNum(99, this.handle, []);
    }

    getRestartMode(): number {
        return callNum(100, this.handle, []);
    }

    getRightHandItem(): number {
        return callNum(101, this.handle, []);
    }

    isMayaAnim(): boolean {
        return callNum(102, this.handle, []) !== 0;
    }

    setRestartMode(a0: number): void {
        callVoid(103, this.handle, [a0]);
    }

}
