// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callVoid, wrap } from './runtime';
import { Animation } from './Animation';
import { Model } from './Model';

export class AnimationController extends ApiObject {
    animate(a0: ApiObject | null): Model | null {
        return wrap(104, this.handle, [(a0 ? a0.handle : -1)], Model);
    }

    animate$Model_AnimationController(a0: ApiObject | null, a1: ApiObject | null): Model | null {
        return wrap(105, this.handle, [(a0 ? a0.handle : -1), (a1 ? a1.handle : -1)], Model);
    }

    getAnimation(): Animation | null {
        return wrap(106, this.handle, [], Animation);
    }

    getFrame(): number {
        return callNum(107, this.handle, []);
    }

    loop(): void {
        callVoid(108, this.handle, []);
    }

    reset(): void {
        callVoid(109, this.handle, []);
    }

    setAnimation(a0: ApiObject | null): void {
        callVoid(110, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setFrame(a0: number): AnimationController | null {
        return wrap(111, this.handle, [a0], AnimationController);
    }

    tick(a0: number): void {
        callVoid(112, this.handle, [a0]);
    }

}
