// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { Actor } from './Actor';

export class AnimationChanged extends ApiObject {
    getActor(): Actor | null {
        return wrap(1611, this.handle, [], Actor);
    }

    hashCode(): number {
        return callNum(1612, this.handle, []);
    }

    setActor(a0: ApiObject | null): void {
        callVoid(1613, this.handle, [(a0 ? a0.handle : -1)]);
    }

    toString(): string | null {
        return callStr(1614, this.handle, []);
    }

}
