// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid } from './runtime';

export class BeforeMenuRender extends ApiObject {
    consume(): void {
        callVoid(1631, this.handle, []);
    }

    hashCode(): number {
        return callNum(1632, this.handle, []);
    }

    isConsumed(): boolean {
        return callNum(1633, this.handle, []) !== 0;
    }

    setConsumed(a0: boolean): void {
        callVoid(1634, this.handle, [(a0 ? 1 : 0)]);
    }

    toString(): string | null {
        return callStr(1635, this.handle, []);
    }

}
