// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum } from './runtime';

export class BufferProvider extends ApiObject {
    getHeight(): number {
        return callNum(113, this.handle, []);
    }

    getPixels(): ApiArray<number> {
        return new ApiArray<number>(callNum(114, this.handle, []), 'num', null);
    }

    getWidth(): number {
        return callNum(115, this.handle, []);
    }

}
