// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, wrap } from './runtime';
import { LocalPoint } from './LocalPoint';
import { WorldView } from './WorldView';

export class CameraFocusableEntity extends ApiObject {
    getCameraFocus(): LocalPoint | null {
        return wrap(116, this.handle, [], LocalPoint);
    }

    getWorldView(): WorldView | null {
        return wrap(117, this.handle, [], WorldView);
    }

}
