// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class ChatPlayer extends ApiObject {
    getName(): string | null {
        return callStr(126, this.handle, []);
    }

    getPrevName(): string | null {
        return callStr(127, this.handle, []);
    }

    getWorld(): number {
        return callNum(128, this.handle, []);
    }

}
