// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callVoid } from './runtime';
import { MessageNode } from './MessageNode';

export class ChatLineBuffer extends ApiObject {
    getLength(): number {
        return callNum(118, this.handle, []);
    }

    getLines(): ApiArray<MessageNode | null> {
        return new ApiArray<MessageNode | null>(callNum(119, this.handle, []), 'handle', MessageNode);
    }

    removeMessageNode(a0: ApiObject | null): void {
        callVoid(120, this.handle, [(a0 ? a0.handle : -1)]);
    }

}
