// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class ChatMessageType extends ApiObject {
    getType(): number {
        return callNum(121, this.handle, []);
    }

    hashCode(): number {
        return callNum(122, this.handle, []);
    }

    name(): string | null {
        return callStr(123, this.handle, []);
    }

    ordinal(): number {
        return callNum(124, this.handle, []);
    }

    toString(): string | null {
        return callStr(125, this.handle, []);
    }

}
