// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callStr, wrap } from './runtime';
import { ClanRank } from './ClanRank';

export class ClanMember extends ApiObject {
    getName(): string | null {
        return callStr(1538, this.handle, []);
    }

    getRank(): ClanRank | null {
        return wrap(1539, this.handle, [], ClanRank);
    }

}
