// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { ClanChannel } from './ClanChannel';
import { ClanChannelMember } from './ClanChannelMember';

export class ClanMemberJoined extends ApiObject {
    getClanChannel(): ClanChannel | null {
        return wrap(1654, this.handle, [], ClanChannel);
    }

    getClanMember(): ClanChannelMember | null {
        return wrap(1655, this.handle, [], ClanChannelMember);
    }

    hashCode(): number {
        return callNum(1656, this.handle, []);
    }

    toString(): string | null {
        return callStr(1657, this.handle, []);
    }

}
