// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class ClanRank extends ApiObject {
    getRank(): number {
        return callNum(1540, this.handle, []);
    }

    hashCode(): number {
        return callNum(1541, this.handle, []);
    }

    toString(): string | null {
        return callStr(1542, this.handle, []);
    }

}
