// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callStr, callStrArg, wrap } from './runtime';
import { ClanChannelMember } from './ClanChannelMember';

export class ClanChannel extends ApiObject {
    findMember(a0: string): ClanChannelMember | null {
        callStrArg(0, a0);
        return wrap(1532, this.handle, [0], ClanChannelMember);
    }

    getName(): string | null {
        return callStr(1533, this.handle, []);
    }

}
