// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { ClanRank } from './ClanRank';

export class ClanChannelMember extends ApiObject {
    getName(): string | null {
        return callStr(1534, this.handle, []);
    }

    getPrevName(): string | null {
        return callStr(1535, this.handle, []);
    }

    getRank(): ClanRank | null {
        return wrap(1536, this.handle, [], ClanRank);
    }

    getWorld(): number {
        return callNum(1537, this.handle, []);
    }

}
