// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class ClanTitle extends ApiObject {
    getId(): number {
        return callNum(1546, this.handle, []);
    }

    getName(): string | null {
        return callStr(1547, this.handle, []);
    }

    hashCode(): number {
        return callNum(1548, this.handle, []);
    }

    toString(): string | null {
        return callStr(1549, this.handle, []);
    }

}
