// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { ClanChannel } from './ClanChannel';

export class ClanChannelChanged extends ApiObject {
    getClanChannel(): ClanChannel | null {
        return wrap(1647, this.handle, [], ClanChannel);
    }

    getClanId(): number {
        return callNum(1648, this.handle, []);
    }

    hashCode(): number {
        return callNum(1649, this.handle, []);
    }

    isGuest(): boolean {
        return callNum(1650, this.handle, []) !== 0;
    }

    toString(): string | null {
        return callStr(1651, this.handle, []);
    }

}
