// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callStr, callStrArg, callVoid, wrap } from './runtime';
import { Animation } from './Animation';
import { BufferProvider } from './BufferProvider';
import { Callbacks } from './Callbacks';
import { CameraFocusableEntity } from './CameraFocusableEntity';
import { ClanChannel } from './ClanChannel';
import { ClanSettings } from './ClanSettings';
import { CollisionData } from './CollisionData';
import { DBRowConfig } from './DBRowConfig';
import { Deque } from './Deque';
import { DrawCallbacks } from './DrawCallbacks';
import { EnumComposition } from './EnumComposition';
import { FriendContainer } from './FriendContainer';
import { FriendsChatManager } from './FriendsChatManager';
import { GrandExchangeOffer } from './GrandExchangeOffer';
import { HashTable } from './HashTable';
import { IndexDataBase } from './IndexDataBase';
import { IndexedSprite } from './IndexedSprite';
import { ItemComposition } from './ItemComposition';
import { ItemContainer } from './ItemContainer';
import { IterableHashTable } from './IterableHashTable';
import { LocalPoint } from './LocalPoint';
import { MapElementConfig } from './MapElementConfig';
import { Menu } from './Menu';
import { MenuEntry } from './MenuEntry';
import { Model } from './Model';
import { ModelData } from './ModelData';
import { NPC } from './NPC';
import { NPCComposition } from './NPCComposition';
import { NameableContainer } from './NameableContainer';
import { NodeCache } from './NodeCache';
import { ObjectComposition } from './ObjectComposition';
import { Player } from './Player';
import { Point } from './Point';
import { Preferences } from './Preferences';
import { Rasterizer } from './Rasterizer';
import { RenderOverview } from './RenderOverview';
import { RuneLiteObject } from './RuneLiteObject';
import { Scene } from './Scene';
import { SpritePixels } from './SpritePixels';
import { StructComposition } from './StructComposition';
import { TextureProvider } from './TextureProvider';
import { Tile } from './Tile';
import { VarbitComposition } from './VarbitComposition';
import { Widget } from './Widget';
import { WidgetConfigNode } from './WidgetConfigNode';
import { WidgetNode } from './WidgetNode';
import { World } from './World';
import { WorldMap } from './WorldMap';
import { WorldPoint } from './WorldPoint';
import { WorldView } from './WorldView';

export class Client extends ApiObject {
    changeMemoryMode(a0: boolean): void {
        callVoid(129, this.handle, [(a0 ? 1 : 0)]);
    }

    changeWorld(a0: ApiObject | null): void {
        callVoid(130, this.handle, [(a0 ? a0.handle : -1)]);
    }

    clearHintArrow(): void {
        callVoid(131, this.handle, []);
    }

    closeInterface(a0: ApiObject | null, a1: boolean): void {
        callVoid(132, this.handle, [(a0 ? a0.handle : -1), (a1 ? 1 : 0)]);
    }

    createIndexedSprite(): IndexedSprite | null {
        return wrap(133, this.handle, [], IndexedSprite);
    }

    createMenuEntry(a0: number): MenuEntry | null {
        return wrap(134, this.handle, [a0], MenuEntry);
    }

    createRuneLiteObject(): RuneLiteObject | null {
        return wrap(135, this.handle, [], RuneLiteObject);
    }

    createWorld(): World | null {
        return wrap(136, this.handle, [], World);
    }

    draw2010Menu(a0: number): void {
        callVoid(137, this.handle, [a0]);
    }

    drawInstanceMap(a0: number): SpritePixels | null {
        return wrap(138, this.handle, [a0], SpritePixels);
    }

    drawOriginalMenu(a0: number): void {
        callVoid(139, this.handle, [a0]);
    }

    findWorldViewFromWorldPoint(a0: ApiObject | null): WorldView | null {
        return wrap(140, this.handle, [(a0 ? a0.handle : -1)], WorldView);
    }

    get3dZoom(): number {
        return callNum(141, this.handle, []);
    }

    getAccountHash(): number {
        return callNum(142, this.handle, []);
    }

    getAccountType(): string | null {
        return callStr(143, this.handle, []);
    }

    getAmbientSoundEffects(): Deque | null {
        return wrap(144, this.handle, [], Deque);
    }

    getAnimationCache(): NodeCache | null {
        return wrap(145, this.handle, [], NodeCache);
    }

    getArray(a0: number): ApiArray<number> {
        return new ApiArray<number>(callNum(146, this.handle, [a0]), 'num', null);
    }

    getArraySizes(a0: number): number {
        return callNum(147, this.handle, [a0]);
    }

    getBaseX(): number {
        return callNum(148, this.handle, []);
    }

    getBaseY(): number {
        return callNum(149, this.handle, []);
    }

    getBoostedSkillLevels(): ApiArray<number> {
        return new ApiArray<number>(callNum(150, this.handle, []), 'num', null);
    }

    getBufferProvider(): BufferProvider | null {
        return wrap(151, this.handle, [], BufferProvider);
    }

    getBuildID(): string | null {
        return callStr(152, this.handle, []);
    }

    getCallbacks(): Callbacks | null {
        return wrap(153, this.handle, [], Callbacks);
    }

    getCameraFocalPointX(): number {
        return callNum(154, this.handle, []);
    }

    getCameraFocalPointY(): number {
        return callNum(155, this.handle, []);
    }

    getCameraFocalPointZ(): number {
        return callNum(156, this.handle, []);
    }

    getCameraFocusEntity(): CameraFocusableEntity | null {
        return wrap(157, this.handle, [], CameraFocusableEntity);
    }

    getCameraFpPitch(): number {
        return callNum(158, this.handle, []);
    }

    getCameraFpX(): number {
        return callNum(159, this.handle, []);
    }

    getCameraFpY(): number {
        return callNum(160, this.handle, []);
    }

    getCameraFpYaw(): number {
        return callNum(161, this.handle, []);
    }

    getCameraFpZ(): number {
        return callNum(162, this.handle, []);
    }

    getCameraMode(): number {
        return callNum(163, this.handle, []);
    }

    getCameraPitch(): number {
        return callNum(164, this.handle, []);
    }

    getCameraPitchTarget(): number {
        return callNum(165, this.handle, []);
    }

    getCameraX(): number {
        return callNum(166, this.handle, []);
    }

    getCameraY(): number {
        return callNum(167, this.handle, []);
    }

    getCameraYaw(): number {
        return callNum(168, this.handle, []);
    }

    getCameraYawTarget(): number {
        return callNum(169, this.handle, []);
    }

    getCameraZ(): number {
        return callNum(170, this.handle, []);
    }

    getCanvasHeight(): number {
        return callNum(171, this.handle, []);
    }

    getCanvasWidth(): number {
        return callNum(172, this.handle, []);
    }

    getCenterX(): number {
        return callNum(173, this.handle, []);
    }

    getCenterY(): number {
        return callNum(174, this.handle, []);
    }

    getClanChannel(): ClanChannel | null {
        return wrap(175, this.handle, [], ClanChannel);
    }

    getClanChannel$int(a0: number): ClanChannel | null {
        return wrap(176, this.handle, [a0], ClanChannel);
    }

    getClanSettings(): ClanSettings | null {
        return wrap(177, this.handle, [], ClanSettings);
    }

    getClanSettings$int(a0: number): ClanSettings | null {
        return wrap(178, this.handle, [a0], ClanSettings);
    }

    getCollisionMaps(): ApiArray<CollisionData | null> {
        return new ApiArray<CollisionData | null>(callNum(179, this.handle, []), 'handle', CollisionData);
    }

    getComponentTable(): HashTable | null {
        return wrap(180, this.handle, [], HashTable);
    }

    getCrossSprites(): ApiArray<SpritePixels | null> {
        return new ApiArray<SpritePixels | null>(callNum(181, this.handle, []), 'handle', SpritePixels);
    }

    getCrossWorldMessageIds(): ApiArray<number> {
        return new ApiArray<number>(callNum(182, this.handle, []), 'num', null);
    }

    getCrossWorldMessageIdsIndex(): number {
        return callNum(183, this.handle, []);
    }

    getCurrentLoginField(): number {
        return callNum(184, this.handle, []);
    }

    getDBRowConfig(a0: number): DBRowConfig | null {
        return wrap(185, this.handle, [a0], DBRowConfig);
    }

    getDBTableField(a0: number, a1: number, a2: number): ApiArray<number> {
        return new ApiArray<number>(callNum(186, this.handle, [a0, a1, a2]), 'none', null);
    }

    getDragTime(): number {
        return callNum(187, this.handle, []);
    }

    getDraggedOnWidget(): Widget | null {
        return wrap(188, this.handle, [], Widget);
    }

    getDraggedWidget(): Widget | null {
        return wrap(189, this.handle, [], Widget);
    }

    getDraw2DMask(): number {
        return callNum(190, this.handle, []);
    }

    getDrawCallbacks(): DrawCallbacks | null {
        return wrap(191, this.handle, [], DrawCallbacks);
    }

    getEnergy(): number {
        return callNum(192, this.handle, []);
    }

    getEnum(a0: number): EnumComposition | null {
        return wrap(193, this.handle, [a0], EnumComposition);
    }

    getEnvironment(): number {
        return callNum(194, this.handle, []);
    }

    getExpandedMapLoading(): number {
        return callNum(195, this.handle, []);
    }

    getFPS(): number {
        return callNum(196, this.handle, []);
    }

    getFocusedInputFieldWidget(): Widget | null {
        return wrap(197, this.handle, [], Widget);
    }

    getFollower(): NPC | null {
        return wrap(198, this.handle, [], NPC);
    }

    getFriendContainer(): FriendContainer | null {
        return wrap(199, this.handle, [], FriendContainer);
    }

    getFriendsChatManager(): FriendsChatManager | null {
        return wrap(200, this.handle, [], FriendsChatManager);
    }

    getGameCycle(): number {
        return callNum(201, this.handle, []);
    }

    getGameState(): string | null {
        return callStr(202, this.handle, []);
    }

    getGrandExchangeOffers(): ApiArray<GrandExchangeOffer | null> {
        return new ApiArray<GrandExchangeOffer | null>(callNum(203, this.handle, []), 'handle', GrandExchangeOffer);
    }

    getGraphicsObjects(): Deque | null {
        return wrap(204, this.handle, [], Deque);
    }

    getGuestClanChannel(): ClanChannel | null {
        return wrap(205, this.handle, [], ClanChannel);
    }

    getGuestClanSettings(): ClanSettings | null {
        return wrap(206, this.handle, [], ClanSettings);
    }

    getHintArrowNpc(): NPC | null {
        return wrap(207, this.handle, [], NPC);
    }

    getHintArrowPlayer(): Player | null {
        return wrap(208, this.handle, [], Player);
    }

    getHintArrowPoint(): WorldPoint | null {
        return wrap(209, this.handle, [], WorldPoint);
    }

    getHintArrowType(): number {
        return callNum(210, this.handle, []);
    }

    getIdleTimeout(): number {
        return callNum(211, this.handle, []);
    }

    getIgnoreContainer(): NameableContainer | null {
        return wrap(212, this.handle, [], NameableContainer);
    }

    getIndex(a0: number): IndexDataBase | null {
        return wrap(213, this.handle, [a0], IndexDataBase);
    }

    getIndexConfig(): IndexDataBase | null {
        return wrap(214, this.handle, [], IndexDataBase);
    }

    getIndexScripts(): IndexDataBase | null {
        return wrap(215, this.handle, [], IndexDataBase);
    }

    getIndexSprites(): IndexDataBase | null {
        return wrap(216, this.handle, [], IndexDataBase);
    }

    getInstanceTemplateChunks(): ApiArray<number> {
        return new ApiArray<number>(callNum(217, this.handle, []), 'none', null);
    }

    getIntStack(): ApiArray<number> {
        return new ApiArray<number>(callNum(218, this.handle, []), 'num', null);
    }

    getIntStackSize(): number {
        return callNum(219, this.handle, []);
    }

    getItemCompositionCache(): NodeCache | null {
        return wrap(220, this.handle, [], NodeCache);
    }

    getItemContainer(a0: number): ItemContainer | null {
        return wrap(221, this.handle, [a0], ItemContainer);
    }

    getItemContainers(): HashTable | null {
        return wrap(222, this.handle, [], HashTable);
    }

    getItemCount(): number {
        return callNum(223, this.handle, []);
    }

    getItemDefinition(a0: number): ItemComposition | null {
        return wrap(224, this.handle, [a0], ItemComposition);
    }

    getItemModelCache(): NodeCache | null {
        return wrap(225, this.handle, [], NodeCache);
    }

    getItemSpriteCache(): NodeCache | null {
        return wrap(226, this.handle, [], NodeCache);
    }

    getKeyboardIdleTicks(): number {
        return callNum(227, this.handle, []);
    }

    getLauncherDisplayName(): string | null {
        return callStr(228, this.handle, []);
    }

    getLocalDestinationLocation(): LocalPoint | null {
        return wrap(229, this.handle, [], LocalPoint);
    }

    getLocalPlayer(): Player | null {
        return wrap(230, this.handle, [], Player);
    }

    getLoginIndex(): number {
        return callNum(231, this.handle, []);
    }

    getMapDots(): ApiArray<SpritePixels | null> {
        return new ApiArray<SpritePixels | null>(callNum(232, this.handle, []), 'handle', SpritePixels);
    }

    getMapElementConfig(a0: number): MapElementConfig | null {
        return wrap(233, this.handle, [a0], MapElementConfig);
    }

    getMapIcons(): ApiArray<SpritePixels | null> {
        return new ApiArray<SpritePixels | null>(callNum(234, this.handle, []), 'handle', SpritePixels);
    }

    getMapRegions(): ApiArray<number> {
        return new ApiArray<number>(callNum(235, this.handle, []), 'num', null);
    }

    getMapScene(): ApiArray<IndexedSprite | null> {
        return new ApiArray<IndexedSprite | null>(callNum(236, this.handle, []), 'handle', IndexedSprite);
    }

    getMenu(): Menu | null {
        return wrap(237, this.handle, [], Menu);
    }

    getMenuEntries(): ApiArray<MenuEntry | null> {
        return new ApiArray<MenuEntry | null>(callNum(238, this.handle, []), 'handle', MenuEntry);
    }

    getMenuHeight(): number {
        return callNum(239, this.handle, []);
    }

    getMenuScroll(): number {
        return callNum(240, this.handle, []);
    }

    getMenuWidth(): number {
        return callNum(241, this.handle, []);
    }

    getMenuX(): number {
        return callNum(242, this.handle, []);
    }

    getMenuY(): number {
        return callNum(243, this.handle, []);
    }

    getMessages(): IterableHashTable | null {
        return wrap(244, this.handle, [], IterableHashTable);
    }

    getMinimapZoom(): number {
        return callNum(245, this.handle, []);
    }

    getModIcons(): ApiArray<IndexedSprite | null> {
        return new ApiArray<IndexedSprite | null>(callNum(246, this.handle, []), 'handle', IndexedSprite);
    }

    getMouseCanvasPosition(): Point | null {
        return wrap(247, this.handle, [], Point);
    }

    getMouseCurrentButton(): number {
        return callNum(248, this.handle, []);
    }

    getMouseIdleTicks(): number {
        return callNum(249, this.handle, []);
    }

    getMouseLastPressedMillis(): number {
        return callNum(250, this.handle, []);
    }

    getMusicVolume(): number {
        return callNum(251, this.handle, []);
    }

    getNpcDefinition(a0: number): NPCComposition | null {
        return wrap(252, this.handle, [a0], NPCComposition);
    }

    getObjectCompositionCache(): NodeCache | null {
        return wrap(253, this.handle, [], NodeCache);
    }

    getObjectDefinition(a0: number): ObjectComposition | null {
        return wrap(254, this.handle, [a0], ObjectComposition);
    }

    getObjectStack(): ApiArray<number> {
        return new ApiArray<number>(callNum(255, this.handle, []), 'none', null);
    }

    getObjectStackSize(): number {
        return callNum(256, this.handle, []);
    }

    getOculusOrbFocalPointX(): number {
        return callNum(257, this.handle, []);
    }

    getOculusOrbFocalPointY(): number {
        return callNum(258, this.handle, []);
    }

    getOculusOrbState(): number {
        return callNum(259, this.handle, []);
    }

    getOverallExperience(): number {
        return callNum(260, this.handle, []);
    }

    getPlane(): number {
        return callNum(261, this.handle, []);
    }

    getPlayerMenuTypes(): ApiArray<number> {
        return new ApiArray<number>(callNum(262, this.handle, []), 'num', null);
    }

    getPlayerOptions(): ApiArray<string | null> {
        return new ApiArray<string | null>(callNum(263, this.handle, []), 'str', null);
    }

    getPlayerOptionsPriorities(): ApiArray<number> {
        return new ApiArray<number>(callNum(264, this.handle, []), 'num', null);
    }

    getPreferences(): Preferences | null {
        return wrap(265, this.handle, [], Preferences);
    }

    getProjectiles(): Deque | null {
        return wrap(266, this.handle, [], Deque);
    }

    getRasterizer(): Rasterizer | null {
        return wrap(267, this.handle, [], Rasterizer);
    }

    getRasterizer3D_clipMidX2(): number {
        return callNum(268, this.handle, []);
    }

    getRasterizer3D_clipMidY2(): number {
        return callNum(269, this.handle, []);
    }

    getRasterizer3D_clipNegativeMidX(): number {
        return callNum(270, this.handle, []);
    }

    getRasterizer3D_clipNegativeMidY(): number {
        return callNum(271, this.handle, []);
    }

    getRealSkillLevels(): ApiArray<number> {
        return new ApiArray<number>(callNum(272, this.handle, []), 'num', null);
    }

    getRenderOverview(): RenderOverview | null {
        return wrap(273, this.handle, [], RenderOverview);
    }

    getRevision(): number {
        return callNum(274, this.handle, []);
    }

    getScale(): number {
        return callNum(275, this.handle, []);
    }

    getScene(): Scene | null {
        return wrap(276, this.handle, [], Scene);
    }

    getScriptActiveWidget(): Widget | null {
        return wrap(277, this.handle, [], Widget);
    }

    getScriptDotWidget(): Widget | null {
        return wrap(278, this.handle, [], Widget);
    }

    getSelectedSceneTile(): Tile | null {
        return wrap(279, this.handle, [], Tile);
    }

    getSelectedWidget(): Widget | null {
        return wrap(280, this.handle, [], Widget);
    }

    getServerVarbitValue(a0: number): number {
        return callNum(281, this.handle, [a0]);
    }

    getServerVarpValue(a0: number): number {
        return callNum(282, this.handle, [a0]);
    }

    getServerVarps(): ApiArray<number> {
        return new ApiArray<number>(callNum(283, this.handle, []), 'num', null);
    }

    getSkillExperiences(): ApiArray<number> {
        return new ApiArray<number>(callNum(284, this.handle, []), 'num', null);
    }

    getSkyboxColor(): number {
        return callNum(285, this.handle, []);
    }

    getSprite(a0: number): SpritePixels | null {
        return wrap(286, this.handle, [a0], SpritePixels);
    }

    getSprite$int_int(a0: number, a1: number): SpritePixels | null {
        return wrap(287, this.handle, [a0, a1], SpritePixels);
    }

    getSprites(a0: ApiObject | null, a1: number, a2: number): ApiArray<SpritePixels | null> {
        return new ApiArray<SpritePixels | null>(callNum(288, this.handle, [(a0 ? a0.handle : -1), a1, a2]), 'handle', SpritePixels);
    }

    getStructComposition(a0: number): StructComposition | null {
        return wrap(289, this.handle, [a0], StructComposition);
    }

    getStructCompositionCache(): NodeCache | null {
        return wrap(290, this.handle, [], NodeCache);
    }

    getTextureProvider(): TextureProvider | null {
        return wrap(291, this.handle, [], TextureProvider);
    }

    getTickCount(): number {
        return callNum(292, this.handle, []);
    }

    getTileHeights(): ApiArray<number> {
        return new ApiArray<number>(callNum(293, this.handle, []), 'none', null);
    }

    getTileSettings(): ApiArray<number> {
        return new ApiArray<number>(callNum(294, this.handle, []), 'none', null);
    }

    getTopLevelInterfaceId(): number {
        return callNum(295, this.handle, []);
    }

    getTopLevelWorldView(): WorldView | null {
        return wrap(296, this.handle, [], WorldView);
    }

    getTotalLevel(): number {
        return callNum(297, this.handle, []);
    }

    getUsername(): string | null {
        return callStr(298, this.handle, []);
    }

    getVar(a0: number): number {
        return callNum(299, this.handle, [a0]);
    }

    getVarbit(a0: number): VarbitComposition | null {
        return wrap(300, this.handle, [a0], VarbitComposition);
    }

    getVarbitValue(a0: number): number {
        return callNum(301, this.handle, [a0]);
    }

    getVarcIntValue(a0: number): number {
        return callNum(302, this.handle, [a0]);
    }

    getVarcStrValue(a0: number): string | null {
        return callStr(303, this.handle, [a0]);
    }

    getVarpValue(a0: number): number {
        return callNum(304, this.handle, [a0]);
    }

    getVarps(): ApiArray<number> {
        return new ApiArray<number>(callNum(305, this.handle, []), 'num', null);
    }

    getViewportHeight(): number {
        return callNum(306, this.handle, []);
    }

    getViewportWidth(): number {
        return callNum(307, this.handle, []);
    }

    getViewportXOffset(): number {
        return callNum(308, this.handle, []);
    }

    getViewportYOffset(): number {
        return callNum(309, this.handle, []);
    }

    getWeight(): number {
        return callNum(310, this.handle, []);
    }

    getWidget(a0: number): Widget | null {
        return wrap(311, this.handle, [a0], Widget);
    }

    getWidget$int_int(a0: number, a1: number): Widget | null {
        return wrap(312, this.handle, [a0, a1], Widget);
    }

    getWidgetConfig(a0: ApiObject | null): WidgetConfigNode | null {
        return wrap(313, this.handle, [(a0 ? a0.handle : -1)], WidgetConfigNode);
    }

    getWidgetFlags(): HashTable | null {
        return wrap(314, this.handle, [], HashTable);
    }

    getWidgetRoots(): ApiArray<Widget | null> {
        return new ApiArray<Widget | null>(callNum(315, this.handle, []), 'handle', Widget);
    }

    getWidgetSpriteCache(): NodeCache | null {
        return wrap(316, this.handle, [], NodeCache);
    }

    getWorld(): number {
        return callNum(317, this.handle, []);
    }

    getWorldHost(): string | null {
        return callStr(318, this.handle, []);
    }

    getWorldList(): ApiArray<World | null> {
        return new ApiArray<World | null>(callNum(319, this.handle, []), 'handle', World);
    }

    getWorldMap(): WorldMap | null {
        return wrap(320, this.handle, [], WorldMap);
    }

    getWorldView(a0: number): WorldView | null {
        return wrap(321, this.handle, [a0], WorldView);
    }

    hasHintArrow(): boolean {
        return callNum(322, this.handle, []) !== 0;
    }

    hopToWorld(a0: ApiObject | null): void {
        callVoid(323, this.handle, [(a0 ? a0.handle : -1)]);
    }

    initialize(): void {
        callVoid(324, this.handle, []);
    }

    invalidateStretching(a0: boolean): void {
        callVoid(325, this.handle, [(a0 ? 1 : 0)]);
    }

    isCameraShakeDisabled(): boolean {
        return callNum(326, this.handle, []) !== 0;
    }

    isClientThread(): boolean {
        return callNum(327, this.handle, []) !== 0;
    }

    isDraggingWidget(): boolean {
        return callNum(328, this.handle, []) !== 0;
    }

    isFriended(a0: string, a1: boolean): boolean {
        callStrArg(0, a0);
        return callNum(329, this.handle, [0, (a1 ? 1 : 0)]) !== 0;
    }

    isGpu(): boolean {
        return callNum(330, this.handle, []) !== 0;
    }

    isInInstancedRegion(): boolean {
        return callNum(331, this.handle, []) !== 0;
    }

    isKeyPressed(a0: number): boolean {
        return callNum(332, this.handle, [a0]) !== 0;
    }

    isMenuOpen(): boolean {
        return callNum(333, this.handle, []) !== 0;
    }

    isMenuScrollable(): boolean {
        return callNum(334, this.handle, []) !== 0;
    }

    isMinimapZoom(): boolean {
        return callNum(335, this.handle, []) !== 0;
    }

    isMouseInSpriteRegion(a0: number, a1: number, a2: ApiObject | null): boolean {
        return callNum(336, this.handle, [a0, a1, (a2 ? a2.handle : -1)]) !== 0;
    }

    isMouseoverTextEnabled(): boolean {
        return callNum(337, this.handle, []) !== 0;
    }

    isOnLoginScreen(): boolean {
        return callNum(338, this.handle, []) !== 0;
    }

    isResized(): boolean {
        return callNum(339, this.handle, []) !== 0;
    }

    isRuneLiteObjectRegistered(a0: ApiObject | null): boolean {
        return callNum(340, this.handle, [(a0 ? a0.handle : -1)]) !== 0;
    }

    isStretchedEnabled(): boolean {
        return callNum(341, this.handle, []) !== 0;
    }

    isStretchedFast(): boolean {
        return callNum(342, this.handle, []) !== 0;
    }

    isWidgetSelected(): boolean {
        return callNum(343, this.handle, []) !== 0;
    }

    loadAnimation(a0: number): Animation | null {
        return wrap(344, this.handle, [a0], Animation);
    }

    loadModel(a0: number): Model | null {
        return wrap(345, this.handle, [a0], Model);
    }

    loadModelData(a0: number): ModelData | null {
        return wrap(346, this.handle, [a0], ModelData);
    }

    newclickInRegion$int_int_SpritePixels(a0: number, a1: number, a2: ApiObject | null): boolean {
        return callNum(347, this.handle, [a0, a1, (a2 ? a2.handle : -1)]) !== 0;
    }

    newclickInRegion(a0: number, a1: number, a2: number, a3: number): boolean {
        return callNum(348, this.handle, [a0, a1, a2, a3]) !== 0;
    }

    newmouseInRegion$int_int_SpritePixels(a0: number, a1: number, a2: ApiObject | null): boolean {
        return callNum(349, this.handle, [a0, a1, (a2 ? a2.handle : -1)]) !== 0;
    }

    newmouseInRegion(a0: number, a1: number, a2: number, a3: number): boolean {
        return callNum(350, this.handle, [a0, a1, a2, a3]) !== 0;
    }

    openInterface(a0: number, a1: number, a2: number): WidgetNode | null {
        return wrap(351, this.handle, [a0, a1, a2], WidgetNode);
    }

    openWorldHopper(): void {
        callVoid(352, this.handle, []);
    }

    playSoundEffect(a0: number): void {
        callVoid(353, this.handle, [a0]);
    }

    playSoundEffect$int_int(a0: number, a1: number): void {
        callVoid(354, this.handle, [a0, a1]);
    }

    playSoundEffect$int_int_int_int(a0: number, a1: number, a2: number, a3: number): void {
        callVoid(355, this.handle, [a0, a1, a2, a3]);
    }

    queueChangedVarp(a0: number): void {
        callVoid(356, this.handle, [a0]);
    }

    refreshChat(): void {
        callVoid(357, this.handle, []);
    }

    registerRuneLiteObject(a0: ApiObject | null): void {
        callVoid(358, this.handle, [(a0 ? a0.handle : -1)]);
    }

    removeRuneLiteObject(a0: ApiObject | null): void {
        callVoid(359, this.handle, [(a0 ? a0.handle : -1)]);
    }

    resetHealthBarCaches(): void {
        callVoid(360, this.handle, []);
    }

    resizeCanvas(): void {
        callVoid(361, this.handle, []);
    }

    setAllWidgetsAreOpTargetable(a0: boolean): void {
        callVoid(362, this.handle, [(a0 ? 1 : 0)]);
    }

    setCameraFocalPointX(a0: number): void {
        callVoid(363, this.handle, [a0]);
    }

    setCameraFocalPointY(a0: number): void {
        callVoid(364, this.handle, [a0]);
    }

    setCameraFocalPointZ(a0: number): void {
        callVoid(365, this.handle, [a0]);
    }

    setCameraMode(a0: number): void {
        callVoid(366, this.handle, [a0]);
    }

    setCameraMouseButtonMask(a0: number): void {
        callVoid(367, this.handle, [a0]);
    }

    setCameraPitchRelaxerEnabled(a0: boolean): void {
        callVoid(368, this.handle, [(a0 ? 1 : 0)]);
    }

    setCameraPitchTarget(a0: number): void {
        callVoid(369, this.handle, [a0]);
    }

    setCameraShakeDisabled(a0: boolean): void {
        callVoid(370, this.handle, [(a0 ? 1 : 0)]);
    }

    setCameraSpeed(a0: number): void {
        callVoid(371, this.handle, [a0]);
    }

    setCameraYawTarget(a0: number): void {
        callVoid(372, this.handle, [a0]);
    }

    setClient(a0: number): void {
        callVoid(373, this.handle, [a0]);
    }

    setCompass(a0: ApiObject | null): void {
        callVoid(374, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setConfiguration(a0: ApiObject | null): void {
        callVoid(375, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setDraggedOnWidget(a0: ApiObject | null): void {
        callVoid(376, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setDraw2DMask(a0: number): void {
        callVoid(377, this.handle, [a0]);
    }

    setDrawCallbacks(a0: ApiObject | null): void {
        callVoid(378, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setExpandedMapLoading(a0: number): void {
        callVoid(379, this.handle, [a0]);
    }

    setFreeCameraSpeed(a0: number): void {
        callVoid(380, this.handle, [a0]);
    }

    setGeSearchResultCount(a0: number): void {
        callVoid(381, this.handle, [a0]);
    }

    setGeSearchResultIndex(a0: number): void {
        callVoid(382, this.handle, [a0]);
    }

    setGpuFlags(a0: number): void {
        callVoid(383, this.handle, [a0]);
    }

    setHintArrow(a0: ApiObject | null): void {
        callVoid(384, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setHintArrow$Player(a0: ApiObject | null): void {
        callVoid(385, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setHintArrow$LocalPoint(a0: ApiObject | null): void {
        callVoid(386, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setHintArrow$WorldPoint(a0: ApiObject | null): void {
        callVoid(387, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setIdleTimeout(a0: number): void {
        callVoid(388, this.handle, [a0]);
    }

    setIntStackSize(a0: number): void {
        callVoid(389, this.handle, [a0]);
    }

    setInventoryDragDelay(a0: number): void {
        callVoid(390, this.handle, [a0]);
    }

    setInvertPitch(a0: boolean): void {
        callVoid(391, this.handle, [(a0 ? 1 : 0)]);
    }

    setInvertYaw(a0: boolean): void {
        callVoid(392, this.handle, [(a0 ? 1 : 0)]);
    }

    setLoginScreen(a0: ApiObject | null): void {
        callVoid(393, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setMenuScroll(a0: number): void {
        callVoid(394, this.handle, [a0]);
    }

    setMinimapTileDrawer(a0: ApiObject | null): void {
        callVoid(395, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setMinimapZoom(a0: boolean): void {
        callVoid(396, this.handle, [(a0 ? 1 : 0)]);
    }

    setMinimapZoom$double(a0: number): void {
        callVoid(397, this.handle, [a0]);
    }

    setMouseoverTextEnabled(a0: boolean): void {
        callVoid(398, this.handle, [(a0 ? 1 : 0)]);
    }

    setMusicVolume(a0: number): void {
        callVoid(399, this.handle, [a0]);
    }

    setObjectStackSize(a0: number): void {
        callVoid(400, this.handle, [a0]);
    }

    setOculusOrbNormalSpeed(a0: number): void {
        callVoid(401, this.handle, [a0]);
    }

    setOculusOrbState(a0: number): void {
        callVoid(402, this.handle, [a0]);
    }

    setOtp(a0: string): void {
        callStrArg(0, a0);
        callVoid(403, this.handle, [0]);
    }

    setPassword(a0: string): void {
        callStrArg(0, a0);
        callVoid(404, this.handle, [0]);
    }

    setScalingFactor(a0: number): void {
        callVoid(405, this.handle, [a0]);
    }

    setShouldRenderLoginScreenFire(a0: boolean): void {
        callVoid(406, this.handle, [(a0 ? 1 : 0)]);
    }

    setSkyboxColor(a0: number): void {
        callVoid(407, this.handle, [a0]);
    }

    setStretchedEnabled(a0: boolean): void {
        callVoid(408, this.handle, [(a0 ? 1 : 0)]);
    }

    setStretchedFast(a0: boolean): void {
        callVoid(409, this.handle, [(a0 ? 1 : 0)]);
    }

    setStretchedIntegerScaling(a0: boolean): void {
        callVoid(410, this.handle, [(a0 ? 1 : 0)]);
    }

    setStretchedKeepAspectRatio(a0: boolean): void {
        callVoid(411, this.handle, [(a0 ? 1 : 0)]);
    }

    setTickCount(a0: number): void {
        callVoid(412, this.handle, [a0]);
    }

    setUnlockedFps(a0: boolean): void {
        callVoid(413, this.handle, [(a0 ? 1 : 0)]);
    }

    setUnlockedFpsTarget(a0: number): void {
        callVoid(414, this.handle, [a0]);
    }

    setUsername(a0: string): void {
        callStrArg(0, a0);
        callVoid(415, this.handle, [0]);
    }

    setVarbit(a0: number, a1: number): void {
        callVoid(416, this.handle, [a0, a1]);
    }

    setVarcIntValue(a0: number, a1: number): void {
        callVoid(417, this.handle, [a0, a1]);
    }

    setVarcStrValue(a0: number, a1: string): void {
        callStrArg(1, a1);
        callVoid(418, this.handle, [a0, 0]);
    }

    setWidgetSelected(a0: boolean): void {
        callVoid(419, this.handle, [(a0 ? 1 : 0)]);
    }

    stopNow(): void {
        callVoid(420, this.handle, []);
    }

    unblockStartup(): void {
        callVoid(421, this.handle, []);
    }

}
