// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum } from './runtime';

export class CollisionData extends ApiObject {
    getFlags(): ApiArray<number> {
        return new ApiArray<number>(callNum(424, this.handle, []), 'none', null);
    }

}
