// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum } from './runtime';

export class ColorTextureOverride extends ApiObject {
    getColorToReplaceWith(): ApiArray<number> {
        return new ApiArray<number>(callNum(425, this.handle, []), 'num', null);
    }

    getTextureToReplaceWith(): ApiArray<number> {
        return new ApiArray<number>(callNum(426, this.handle, []), 'num', null);
    }

}
