// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callStr } from './runtime';

export class CommandExecuted extends ApiObject {
    getArguments(): ApiArray<string | null> {
        return new ApiArray<string | null>(callNum(1660, this.handle, []), 'str', null);
    }

    getCommand(): string | null {
        return callStr(1661, this.handle, []);
    }

    hashCode(): number {
        return callNum(1662, this.handle, []);
    }

    toString(): string | null {
        return callStr(1663, this.handle, []);
    }

}
