// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum } from './runtime';

export class DBRowConfig extends ApiObject {
    getTableID(): number {
        return callNum(1602, this.handle, []);
    }

}
