// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { DecorativeObject } from './DecorativeObject';
import { Tile } from './Tile';

export class DecorativeObjectDespawned extends ApiObject {
    getDecorativeObject(): DecorativeObject | null {
        return wrap(1666, this.handle, [], DecorativeObject);
    }

    getTile(): Tile | null {
        return wrap(1667, this.handle, [], Tile);
    }

    hashCode(): number {
        return callNum(1668, this.handle, []);
    }

    setDecorativeObject(a0: ApiObject | null): void {
        callVoid(1669, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setTile(a0: ApiObject | null): void {
        callVoid(1670, this.handle, [(a0 ? a0.handle : -1)]);
    }

    toString(): string | null {
        return callStr(1671, this.handle, []);
    }

}
