// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { DecorativeObject } from './DecorativeObject';
import { Tile } from './Tile';

export class DecorativeObjectSpawned extends ApiObject {
    getDecorativeObject(): DecorativeObject | null {
        return wrap(1672, this.handle, [], DecorativeObject);
    }

    getTile(): Tile | null {
        return wrap(1673, this.handle, [], Tile);
    }

    hashCode(): number {
        return callNum(1674, this.handle, []);
    }

    setDecorativeObject(a0: ApiObject | null): void {
        callVoid(1675, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setTile(a0: ApiObject | null): void {
        callVoid(1676, this.handle, [(a0 ? a0.handle : -1)]);
    }

    toString(): string | null {
        return callStr(1677, this.handle, []);
    }

}
