// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callVoid } from './runtime';

export class Deque extends ApiObject {
    clear(): void {
        callVoid(446, this.handle, []);
    }

}
