// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class Direction extends ApiObject {
    hashCode(): number {
        return callNum(1554, this.handle, []);
    }

    name(): string | null {
        return callStr(1555, this.handle, []);
    }

    ordinal(): number {
        return callNum(1556, this.handle, []);
    }

    toString(): string | null {
        return callStr(1557, this.handle, []);
    }

}
