// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callVoid } from './runtime';

export class DrawCallbacks extends ApiObject {
    animate(a0: ApiObject | null, a1: number): void {
        callVoid(1966, this.handle, [(a0 ? a0.handle : -1), a1]);
    }

    despawnWorldView(a0: ApiObject | null): void {
        callVoid(1967, this.handle, [(a0 ? a0.handle : -1)]);
    }

    draw(a0: number): void {
        callVoid(1968, this.handle, [a0]);
    }

    drawPass(a0: ApiObject | null, a1: ApiObject | null, a2: number): void {
        callVoid(1969, this.handle, [(a0 ? a0.handle : -1), (a1 ? a1.handle : -1), a2]);
    }

    drawSceneTileModel(a0: ApiObject | null, a1: ApiObject | null, a2: number, a3: number): void {
        callVoid(1970, this.handle, [(a0 ? a0.handle : -1), (a1 ? a1.handle : -1), a2, a3]);
    }

    drawZoneOpaque(a0: ApiObject | null, a1: ApiObject | null, a2: number, a3: number): void {
        callVoid(1971, this.handle, [(a0 ? a0.handle : -1), (a1 ? a1.handle : -1), a2, a3]);
    }

    invalidateZone(a0: ApiObject | null, a1: number, a2: number): void {
        callVoid(1972, this.handle, [(a0 ? a0.handle : -1), a1, a2]);
    }

    loadScene(a0: ApiObject | null): void {
        callVoid(1973, this.handle, [(a0 ? a0.handle : -1)]);
    }

    loadScene$WorldView_Scene(a0: ApiObject | null, a1: ApiObject | null): void {
        callVoid(1974, this.handle, [(a0 ? a0.handle : -1), (a1 ? a1.handle : -1)]);
    }

    postDrawScene(): void {
        callVoid(1975, this.handle, []);
    }

    postSceneDraw(a0: ApiObject | null): void {
        callVoid(1976, this.handle, [(a0 ? a0.handle : -1)]);
    }

    swapScene(a0: ApiObject | null): void {
        callVoid(1977, this.handle, [(a0 ? a0.handle : -1)]);
    }

    zoneInFrustum(a0: number, a1: number, a2: number, a3: number): boolean {
        return callNum(1978, this.handle, [a0, a1, a2, a3]) !== 0;
    }

}
