// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class EquipmentInventorySlot extends ApiObject {
    getSlotIdx(): number {
        return callNum(471, this.handle, []);
    }

    hashCode(): number {
        return callNum(472, this.handle, []);
    }

    name(): string | null {
        return callStr(473, this.handle, []);
    }

    ordinal(): number {
        return callNum(474, this.handle, []);
    }

    toString(): string | null {
        return callStr(475, this.handle, []);
    }

}
