// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject } from './runtime';
import { ActorDeath } from './ActorDeath';
import { AmbientSoundEffectCreated } from './AmbientSoundEffectCreated';
import { AnimationChanged } from './AnimationChanged';
import { AreaSoundEffectPlayed } from './AreaSoundEffectPlayed';
import { BeforeMenuRender } from './BeforeMenuRender';
import { ChatMessage } from './ChatMessage';
import { ClanChannelChanged } from './ClanChannelChanged';
import { ClanMemberJoined } from './ClanMemberJoined';
import { ClanMemberLeft } from './ClanMemberLeft';
import { CommandExecuted } from './CommandExecuted';
import { DecorativeObjectDespawned } from './DecorativeObjectDespawned';
import { DecorativeObjectSpawned } from './DecorativeObjectSpawned';
import { FakeXpDrop } from './FakeXpDrop';
import { FocusChanged } from './FocusChanged';
import { FriendsChatChanged } from './FriendsChatChanged';
import { FriendsChatMemberJoined } from './FriendsChatMemberJoined';
import { FriendsChatMemberLeft } from './FriendsChatMemberLeft';
import { GameObjectDespawned } from './GameObjectDespawned';
import { GameObjectSpawned } from './GameObjectSpawned';
import { GameStateChanged } from './GameStateChanged';
import { GameTick } from './GameTick';
import { GrandExchangeOfferChanged } from './GrandExchangeOfferChanged';
import { GrandExchangeSearched } from './GrandExchangeSearched';
import { GraphicChanged } from './GraphicChanged';
import { GraphicsObjectCreated } from './GraphicsObjectCreated';
import { GroundObjectDespawned } from './GroundObjectDespawned';
import { GroundObjectSpawned } from './GroundObjectSpawned';
import { HitsplatApplied } from './HitsplatApplied';
import { InteractingChanged } from './InteractingChanged';
import { ItemContainerChanged } from './ItemContainerChanged';
import { ItemDespawned } from './ItemDespawned';
import { ItemQuantityChanged } from './ItemQuantityChanged';
import { ItemSpawned } from './ItemSpawned';
import { MenuEntryAdded } from './MenuEntryAdded';
import { MenuOpened } from './MenuOpened';
import { MenuOptionClicked } from './MenuOptionClicked';
import { MenuShouldLeftClick } from './MenuShouldLeftClick';
import { NameableNameChanged } from './NameableNameChanged';
import { NpcChanged } from './NpcChanged';
import { NpcDespawned } from './NpcDespawned';
import { NpcSpawned } from './NpcSpawned';
import { OverheadTextChanged } from './OverheadTextChanged';
import { PlayerChanged } from './PlayerChanged';
import { PlayerDespawned } from './PlayerDespawned';
import { PlayerMenuOptionsChanged } from './PlayerMenuOptionsChanged';
import { PlayerSpawned } from './PlayerSpawned';
import { PostAnimation } from './PostAnimation';
import { PostHealthBarConfig } from './PostHealthBarConfig';
import { PostItemComposition } from './PostItemComposition';
import { PostObjectComposition } from './PostObjectComposition';
import { PostStructComposition } from './PostStructComposition';
import { PreMapLoad } from './PreMapLoad';
import { ProjectileMoved } from './ProjectileMoved';
import { RemovedFriend } from './RemovedFriend';
import { ResizeableChanged } from './ResizeableChanged';
import { ScriptCallbackEvent } from './ScriptCallbackEvent';
import { ScriptPostFired } from './ScriptPostFired';
import { ScriptPreFired } from './ScriptPreFired';
import { SoundEffectPlayed } from './SoundEffectPlayed';
import { StatChanged } from './StatChanged';
import { VarClientIntChanged } from './VarClientIntChanged';
import { VarClientStrChanged } from './VarClientStrChanged';
import { VarbitChanged } from './VarbitChanged';
import { VolumeChanged } from './VolumeChanged';
import { WallObjectDespawned } from './WallObjectDespawned';
import { WallObjectSpawned } from './WallObjectSpawned';
import { WidgetClosed } from './WidgetClosed';
import { WidgetLoaded } from './WidgetLoaded';
import { WorldEntityDespawned } from './WorldEntityDespawned';
import { WorldEntitySpawned } from './WorldEntitySpawned';
import { WorldListLoad } from './WorldListLoad';
import { WorldViewLoaded } from './WorldViewLoaded';
import { WorldViewUnloaded } from './WorldViewUnloaded';

/** Event name to the id the client posts it under. */
export const EVENT_IDS = {
    AccountHashChanged: 0,
    ActorDeath: 1,
    AmbientSoundEffectCreated: 2,
    AnimationChanged: 3,
    AreaSoundEffectPlayed: 4,
    BeforeMenuRender: 5,
    BeforeRender: 6,
    CanvasSizeChanged: 7,
    ChatMessage: 8,
    ClanChannelChanged: 9,
    ClanMemberJoined: 10,
    ClanMemberLeft: 11,
    ClientTick: 12,
    CommandExecuted: 13,
    DecorativeObjectDespawned: 14,
    DecorativeObjectSpawned: 15,
    FakeXpDrop: 16,
    FocusChanged: 17,
    FriendsChatChanged: 18,
    FriendsChatMemberJoined: 19,
    FriendsChatMemberLeft: 20,
    GameObjectDespawned: 21,
    GameObjectSpawned: 22,
    GameStateChanged: 23,
    GameTick: 24,
    GrandExchangeOfferChanged: 25,
    GrandExchangeSearched: 26,
    GraphicChanged: 27,
    GraphicsObjectCreated: 28,
    GroundObjectDespawned: 29,
    GroundObjectSpawned: 30,
    HitsplatApplied: 31,
    InteractingChanged: 32,
    ItemContainerChanged: 33,
    ItemDespawned: 34,
    ItemQuantityChanged: 35,
    ItemSpawned: 36,
    MenuEntryAdded: 37,
    MenuOpened: 38,
    MenuOptionClicked: 39,
    MenuShouldLeftClick: 40,
    NameableNameChanged: 41,
    NpcChanged: 42,
    NpcDespawned: 43,
    NpcSpawned: 44,
    OverheadTextChanged: 45,
    PlayerChanged: 46,
    PlayerDespawned: 47,
    PlayerMenuOptionsChanged: 48,
    PlayerSpawned: 49,
    PostAnimation: 50,
    PostClientTick: 51,
    PostHealthBarConfig: 52,
    PostItemComposition: 53,
    PostMenuSort: 54,
    PostObjectComposition: 55,
    PostStructComposition: 56,
    PreMapLoad: 57,
    ProjectileMoved: 58,
    RemovedFriend: 59,
    ResizeableChanged: 60,
    ScriptCallbackEvent: 61,
    ScriptPostFired: 62,
    ScriptPreFired: 63,
    SoundEffectPlayed: 64,
    StatChanged: 65,
    UsernameChanged: 66,
    VarClientIntChanged: 67,
    VarClientStrChanged: 68,
    VarbitChanged: 69,
    VolumeChanged: 70,
    WallObjectDespawned: 71,
    WallObjectSpawned: 72,
    WidgetClosed: 73,
    WidgetDrag: 74,
    WidgetLoaded: 75,
    WorldChanged: 76,
    WorldEntityDespawned: 77,
    WorldEntitySpawned: 78,
    WorldListLoad: 79,
    WorldViewLoaded: 80,
    WorldViewUnloaded: 81,
} as const;

/** The type a handler receives, by event name. */
export interface FluxEventMap {
    AccountHashChanged: ApiObject;
    ActorDeath: ActorDeath;
    AmbientSoundEffectCreated: AmbientSoundEffectCreated;
    AnimationChanged: AnimationChanged;
    AreaSoundEffectPlayed: AreaSoundEffectPlayed;
    BeforeMenuRender: BeforeMenuRender;
    BeforeRender: ApiObject;
    CanvasSizeChanged: ApiObject;
    ChatMessage: ChatMessage;
    ClanChannelChanged: ClanChannelChanged;
    ClanMemberJoined: ClanMemberJoined;
    ClanMemberLeft: ClanMemberLeft;
    ClientTick: ApiObject;
    CommandExecuted: CommandExecuted;
    DecorativeObjectDespawned: DecorativeObjectDespawned;
    DecorativeObjectSpawned: DecorativeObjectSpawned;
    FakeXpDrop: FakeXpDrop;
    FocusChanged: FocusChanged;
    FriendsChatChanged: FriendsChatChanged;
    FriendsChatMemberJoined: FriendsChatMemberJoined;
    FriendsChatMemberLeft: FriendsChatMemberLeft;
    GameObjectDespawned: GameObjectDespawned;
    GameObjectSpawned: GameObjectSpawned;
    GameStateChanged: GameStateChanged;
    GameTick: GameTick;
    GrandExchangeOfferChanged: GrandExchangeOfferChanged;
    GrandExchangeSearched: GrandExchangeSearched;
    GraphicChanged: GraphicChanged;
    GraphicsObjectCreated: GraphicsObjectCreated;
    GroundObjectDespawned: GroundObjectDespawned;
    GroundObjectSpawned: GroundObjectSpawned;
    HitsplatApplied: HitsplatApplied;
    InteractingChanged: InteractingChanged;
    ItemContainerChanged: ItemContainerChanged;
    ItemDespawned: ItemDespawned;
    ItemQuantityChanged: ItemQuantityChanged;
    ItemSpawned: ItemSpawned;
    MenuEntryAdded: MenuEntryAdded;
    MenuOpened: MenuOpened;
    MenuOptionClicked: MenuOptionClicked;
    MenuShouldLeftClick: MenuShouldLeftClick;
    NameableNameChanged: NameableNameChanged;
    NpcChanged: NpcChanged;
    NpcDespawned: NpcDespawned;
    NpcSpawned: NpcSpawned;
    OverheadTextChanged: OverheadTextChanged;
    PlayerChanged: PlayerChanged;
    PlayerDespawned: PlayerDespawned;
    PlayerMenuOptionsChanged: PlayerMenuOptionsChanged;
    PlayerSpawned: PlayerSpawned;
    PostAnimation: PostAnimation;
    PostClientTick: ApiObject;
    PostHealthBarConfig: PostHealthBarConfig;
    PostItemComposition: PostItemComposition;
    PostMenuSort: ApiObject;
    PostObjectComposition: PostObjectComposition;
    PostStructComposition: PostStructComposition;
    PreMapLoad: PreMapLoad;
    ProjectileMoved: ProjectileMoved;
    RemovedFriend: RemovedFriend;
    ResizeableChanged: ResizeableChanged;
    ScriptCallbackEvent: ScriptCallbackEvent;
    ScriptPostFired: ScriptPostFired;
    ScriptPreFired: ScriptPreFired;
    SoundEffectPlayed: SoundEffectPlayed;
    StatChanged: StatChanged;
    UsernameChanged: ApiObject;
    VarClientIntChanged: VarClientIntChanged;
    VarClientStrChanged: VarClientStrChanged;
    VarbitChanged: VarbitChanged;
    VolumeChanged: VolumeChanged;
    WallObjectDespawned: WallObjectDespawned;
    WallObjectSpawned: WallObjectSpawned;
    WidgetClosed: WidgetClosed;
    WidgetDrag: ApiObject;
    WidgetLoaded: WidgetLoaded;
    WorldChanged: ApiObject;
    WorldEntityDespawned: WorldEntityDespawned;
    WorldEntitySpawned: WorldEntitySpawned;
    WorldListLoad: WorldListLoad;
    WorldViewLoaded: WorldViewLoaded;
    WorldViewUnloaded: WorldViewUnloaded;
}

export type FluxEventName = keyof FluxEventMap;

/** Wrapper constructors indexed by event id, for dispatching a posted handle. */
export const EVENT_CLASSES: Array<new (handle: number) => ApiObject> = [
    ApiObject,
    ActorDeath,
    AmbientSoundEffectCreated,
    AnimationChanged,
    AreaSoundEffectPlayed,
    BeforeMenuRender,
    ApiObject,
    ApiObject,
    ChatMessage,
    ClanChannelChanged,
    ClanMemberJoined,
    ClanMemberLeft,
    ApiObject,
    CommandExecuted,
    DecorativeObjectDespawned,
    DecorativeObjectSpawned,
    FakeXpDrop,
    FocusChanged,
    FriendsChatChanged,
    FriendsChatMemberJoined,
    FriendsChatMemberLeft,
    GameObjectDespawned,
    GameObjectSpawned,
    GameStateChanged,
    GameTick,
    GrandExchangeOfferChanged,
    GrandExchangeSearched,
    GraphicChanged,
    GraphicsObjectCreated,
    GroundObjectDespawned,
    GroundObjectSpawned,
    HitsplatApplied,
    InteractingChanged,
    ItemContainerChanged,
    ItemDespawned,
    ItemQuantityChanged,
    ItemSpawned,
    MenuEntryAdded,
    MenuOpened,
    MenuOptionClicked,
    MenuShouldLeftClick,
    NameableNameChanged,
    NpcChanged,
    NpcDespawned,
    NpcSpawned,
    OverheadTextChanged,
    PlayerChanged,
    PlayerDespawned,
    PlayerMenuOptionsChanged,
    PlayerSpawned,
    PostAnimation,
    ApiObject,
    PostHealthBarConfig,
    PostItemComposition,
    ApiObject,
    PostObjectComposition,
    PostStructComposition,
    PreMapLoad,
    ProjectileMoved,
    RemovedFriend,
    ResizeableChanged,
    ScriptCallbackEvent,
    ScriptPostFired,
    ScriptPreFired,
    SoundEffectPlayed,
    StatChanged,
    ApiObject,
    VarClientIntChanged,
    VarClientStrChanged,
    VarbitChanged,
    VolumeChanged,
    WallObjectDespawned,
    WallObjectSpawned,
    WidgetClosed,
    ApiObject,
    WidgetLoaded,
    ApiObject,
    WorldEntityDespawned,
    WorldEntitySpawned,
    WorldListLoad,
    WorldViewLoaded,
    WorldViewUnloaded,
];
