// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class FakeXpDrop extends ApiObject {
    getSkill(): string | null {
        return callStr(1678, this.handle, []);
    }

    getXp(): number {
        return callNum(1679, this.handle, []);
    }

    hashCode(): number {
        return callNum(1680, this.handle, []);
    }

    toString(): string | null {
        return callStr(1681, this.handle, []);
    }

}
