// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum } from './runtime';

export class FloatProjection extends ApiObject {
    getProjection(): ApiArray<number> {
        return new ApiArray<number>(callNum(478, this.handle, []), 'num', null);
    }

    project(a0: number, a1: number, a2: number): ApiArray<number> {
        return new ApiArray<number>(callNum(479, this.handle, [a0, a1, a2]), 'num', null);
    }

}
