// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid } from './runtime';

export class FocusChanged extends ApiObject {
    hashCode(): number {
        return callNum(1682, this.handle, []);
    }

    isFocused(): boolean {
        return callNum(1683, this.handle, []) !== 0;
    }

    setFocused(a0: boolean): void {
        callVoid(1684, this.handle, [(a0 ? 1 : 0)]);
    }

    toString(): string | null {
        return callStr(1685, this.handle, []);
    }

}
