// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStrArg } from './runtime';

export class FontTypeFace extends ApiObject {
    getBaseline(): number {
        return callNum(480, this.handle, []);
    }

    getTextWidth(a0: string): number {
        callStrArg(0, a0);
        return callNum(481, this.handle, [0]);
    }

}
