// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class FriendsChatMember extends ApiObject {
    getName(): string | null {
        return callStr(498, this.handle, []);
    }

    getPrevName(): string | null {
        return callStr(499, this.handle, []);
    }

    getRank(): string | null {
        return callStr(500, this.handle, []);
    }

    getWorld(): number {
        return callNum(501, this.handle, []);
    }

}
