// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class Friend extends ApiObject {
    getName(): string | null {
        return callStr(482, this.handle, []);
    }

    getPrevName(): string | null {
        return callStr(483, this.handle, []);
    }

    getWorld(): number {
        return callNum(484, this.handle, []);
    }

}
