// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class Friend extends ApiObject {
    getName(): string | null {
        return callStr(480, this.handle, []);
    }

    getPrevName(): string | null {
        return callStr(481, this.handle, []);
    }

    getWorld(): number {
        return callNum(482, this.handle, []);
    }

}
