// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callStrArg, wrap } from './runtime';
import { Deque } from './Deque';
import { Nameable } from './Nameable';

export class FriendContainer extends ApiObject {
    findByName(a0: string): Nameable | null {
        callStrArg(0, a0);
        return wrap(485, this.handle, [0], Nameable);
    }

    getCount(): number {
        return callNum(486, this.handle, []);
    }

    getMembers(): ApiArray<Nameable | null> {
        return new ApiArray<Nameable | null>(callNum(487, this.handle, []), 'handle', Nameable);
    }

    getPendingLogins(): Deque | null {
        return wrap(488, this.handle, [], Deque);
    }

    getSize(): number {
        return callNum(489, this.handle, []);
    }

}
