// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { FriendsChatMember } from './FriendsChatMember';

export class FriendsChatMemberLeft extends ApiObject {
    getMember(): FriendsChatMember | null {
        return wrap(1690, this.handle, [], FriendsChatMember);
    }

    hashCode(): number {
        return callNum(1691, this.handle, []);
    }

    toString(): string | null {
        return callStr(1692, this.handle, []);
    }

}
