// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class FriendsChatRank extends ApiObject {
    getValue(): number {
        return callNum(500, this.handle, []);
    }

    hashCode(): number {
        return callNum(501, this.handle, []);
    }

    name(): string | null {
        return callStr(502, this.handle, []);
    }

    ordinal(): number {
        return callNum(503, this.handle, []);
    }

    toString(): string | null {
        return callStr(504, this.handle, []);
    }

}
