// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class FriendsChatChanged extends ApiObject {
    hashCode(): number {
        return callNum(1684, this.handle, []);
    }

    isJoined(): boolean {
        return callNum(1685, this.handle, []) !== 0;
    }

    toString(): string | null {
        return callStr(1686, this.handle, []);
    }

}
