// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { FriendsChatMember } from './FriendsChatMember';

export class FriendsChatMemberJoined extends ApiObject {
    getMember(): FriendsChatMember | null {
        return wrap(1687, this.handle, [], FriendsChatMember);
    }

    hashCode(): number {
        return callNum(1688, this.handle, []);
    }

    toString(): string | null {
        return callStr(1689, this.handle, []);
    }

}
