// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class GameTick extends ApiObject {
    hashCode(): number {
        return callNum(1710, this.handle, []);
    }

    toString(): string | null {
        return callStr(1711, this.handle, []);
    }

}
