// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class GameStateChanged extends ApiObject {
    getGameState(): string | null {
        return callStr(1707, this.handle, []);
    }

    hashCode(): number {
        return callNum(1708, this.handle, []);
    }

    toString(): string | null {
        return callStr(1709, this.handle, []);
    }

}
