// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callVoid } from './runtime';

export class GameEngine extends ApiObject {
    initialize(): void {
        callVoid(505, this.handle, []);
    }

    isClientThread(): boolean {
        return callNum(506, this.handle, []) !== 0;
    }

    resizeCanvas(): void {
        callVoid(507, this.handle, []);
    }

    setConfiguration(a0: ApiObject | null): void {
        callVoid(508, this.handle, [(a0 ? a0.handle : -1)]);
    }

    unblockStartup(): void {
        callVoid(509, this.handle, []);
    }

}
