// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class GameState extends ApiObject {
    getState(): number {
        return callNum(534, this.handle, []);
    }

    hashCode(): number {
        return callNum(535, this.handle, []);
    }

    name(): string | null {
        return callStr(536, this.handle, []);
    }

    ordinal(): number {
        return callNum(537, this.handle, []);
    }

    toString(): string | null {
        return callStr(538, this.handle, []);
    }

}
