// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { LocalPoint } from './LocalPoint';
import { Point } from './Point';
import { Renderable } from './Renderable';
import { WorldPoint } from './WorldPoint';
import { WorldView } from './WorldView';

export class GameObject extends ApiObject {
    getCanvasLocation(): Point | null {
        return wrap(510, this.handle, [], Point);
    }

    getCanvasLocation$int(a0: number): Point | null {
        return wrap(511, this.handle, [a0], Point);
    }

    getConfig(): number {
        return callNum(512, this.handle, []);
    }

    getHash(): number {
        return callNum(513, this.handle, []);
    }

    getId(): number {
        return callNum(514, this.handle, []);
    }

    getLocalLocation(): LocalPoint | null {
        return wrap(515, this.handle, [], LocalPoint);
    }

    getMinimapLocation(): Point | null {
        return wrap(516, this.handle, [], Point);
    }

    getModelOrientation(): number {
        return callNum(517, this.handle, []);
    }

    getOpOverride(a0: number): string | null {
        return callStr(518, this.handle, [a0]);
    }

    getOrientation(): number {
        return callNum(519, this.handle, []);
    }

    getPlane(): number {
        return callNum(520, this.handle, []);
    }

    getRenderable(): Renderable | null {
        return wrap(521, this.handle, [], Renderable);
    }

    getSceneMaxLocation(): Point | null {
        return wrap(522, this.handle, [], Point);
    }

    getSceneMinLocation(): Point | null {
        return wrap(523, this.handle, [], Point);
    }

    getWorldLocation(): WorldPoint | null {
        return wrap(524, this.handle, [], WorldPoint);
    }

    getWorldView(): WorldView | null {
        return wrap(525, this.handle, [], WorldView);
    }

    getX(): number {
        return callNum(526, this.handle, []);
    }

    getY(): number {
        return callNum(527, this.handle, []);
    }

    getZ(): number {
        return callNum(528, this.handle, []);
    }

    isOpShown(a0: number): boolean {
        return callNum(529, this.handle, [a0]) !== 0;
    }

    sizeX(): number {
        return callNum(530, this.handle, []);
    }

    sizeY(): number {
        return callNum(531, this.handle, []);
    }

}
