// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class GrandExchangeOfferState extends ApiObject {
    hashCode(): number {
        return callNum(545, this.handle, []);
    }

    name(): string | null {
        return callStr(546, this.handle, []);
    }

    ordinal(): number {
        return callNum(547, this.handle, []);
    }

    toString(): string | null {
        return callStr(548, this.handle, []);
    }

}
