// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid } from './runtime';

export class GrandExchangeSearched extends ApiObject {
    consume(): void {
        callVoid(1716, this.handle, []);
    }

    hashCode(): number {
        return callNum(1717, this.handle, []);
    }

    isConsumed(): boolean {
        return callNum(1718, this.handle, []) !== 0;
    }

    setConsumed(a0: boolean): void {
        callVoid(1719, this.handle, [(a0 ? 1 : 0)]);
    }

    toString(): string | null {
        return callStr(1720, this.handle, []);
    }

}
