// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { GraphicsObject } from './GraphicsObject';

export class GraphicsObjectCreated extends ApiObject {
    getGraphicsObject(): GraphicsObject | null {
        return wrap(1725, this.handle, [], GraphicsObject);
    }

    hashCode(): number {
        return callNum(1726, this.handle, []);
    }

    toString(): string | null {
        return callStr(1727, this.handle, []);
    }

}
