// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { GroundObject } from './GroundObject';
import { Tile } from './Tile';

export class GroundObjectDespawned extends ApiObject {
    getGroundObject(): GroundObject | null {
        return wrap(1728, this.handle, [], GroundObject);
    }

    getTile(): Tile | null {
        return wrap(1729, this.handle, [], Tile);
    }

    hashCode(): number {
        return callNum(1730, this.handle, []);
    }

    setGroundObject(a0: ApiObject | null): void {
        callVoid(1731, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setTile(a0: ApiObject | null): void {
        callVoid(1732, this.handle, [(a0 ? a0.handle : -1)]);
    }

    toString(): string | null {
        return callStr(1733, this.handle, []);
    }

}
