// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { GroundObject } from './GroundObject';
import { Tile } from './Tile';

export class GroundObjectSpawned extends ApiObject {
    getGroundObject(): GroundObject | null {
        return wrap(1734, this.handle, [], GroundObject);
    }

    getTile(): Tile | null {
        return wrap(1735, this.handle, [], Tile);
    }

    hashCode(): number {
        return callNum(1736, this.handle, []);
    }

    setGroundObject(a0: ApiObject | null): void {
        callVoid(1737, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setTile(a0: ApiObject | null): void {
        callVoid(1738, this.handle, [(a0 ? a0.handle : -1)]);
    }

    toString(): string | null {
        return callStr(1739, this.handle, []);
    }

}
