// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, wrap } from './runtime';
import { Node } from './Node';

export class HashTable extends ApiObject {
    get(a0: number): Node | null {
        return wrap(581, this.handle, [a0], Node);
    }

}
