// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class HeadIcon extends ApiObject {
    hashCode(): number {
        return callNum(584, this.handle, []);
    }

    name(): string | null {
        return callStr(585, this.handle, []);
    }

    ordinal(): number {
        return callNum(586, this.handle, []);
    }

    toString(): string | null {
        return callStr(587, this.handle, []);
    }

}
