// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callVoid, wrap } from './runtime';
import { SpritePixels } from './SpritePixels';

export class HealthBarConfig extends ApiObject {
    getHealthBarBackSprite(): SpritePixels | null {
        return wrap(588, this.handle, [], SpritePixels);
    }

    getHealthBarFrontSprite(): SpritePixels | null {
        return wrap(589, this.handle, [], SpritePixels);
    }

    getHealthBarFrontSpriteId(): number {
        return callNum(590, this.handle, []);
    }

    setPadding(a0: number): void {
        callVoid(591, this.handle, [a0]);
    }

}
