// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { Actor } from './Actor';
import { Hitsplat } from './Hitsplat';

export class HitsplatApplied extends ApiObject {
    getActor(): Actor | null {
        return wrap(1742, this.handle, [], Actor);
    }

    getHitsplat(): Hitsplat | null {
        return wrap(1743, this.handle, [], Hitsplat);
    }

    hashCode(): number {
        return callNum(1744, this.handle, []);
    }

    setActor(a0: ApiObject | null): void {
        callVoid(1745, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setHitsplat(a0: ApiObject | null): void {
        callVoid(1746, this.handle, [(a0 ? a0.handle : -1)]);
    }

    toString(): string | null {
        return callStr(1747, this.handle, []);
    }

}
