// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum } from './runtime';

export class Hitsplat extends ApiObject {
    getAmount(): number {
        return callNum(592, this.handle, []);
    }

    getDisappearsOnGameCycle(): number {
        return callNum(593, this.handle, []);
    }

    getHitsplatType(): number {
        return callNum(594, this.handle, []);
    }

    isMine(): boolean {
        return callNum(595, this.handle, []) !== 0;
    }

    isOthers(): boolean {
        return callNum(596, this.handle, []) !== 0;
    }

}
