// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class IconID extends ApiObject {
    getIndex(): number {
        return callNum(597, this.handle, []);
    }

    hashCode(): number {
        return callNum(598, this.handle, []);
    }

    name(): string | null {
        return callStr(599, this.handle, []);
    }

    ordinal(): number {
        return callNum(600, this.handle, []);
    }

    toString(): string | null {
        return callStr(601, this.handle, []);
    }

}
