// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callStr } from './runtime';

export class Ignore extends ApiObject {
    getName(): string | null {
        return callStr(602, this.handle, []);
    }

    getPrevName(): string | null {
        return callStr(603, this.handle, []);
    }

}
