// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callStr } from './runtime';

export class Ignore extends ApiObject {
    getName(): string | null {
        return callStr(600, this.handle, []);
    }

    getPrevName(): string | null {
        return callStr(601, this.handle, []);
    }

}
