// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callVoid } from './runtime';

export class IndexedSprite extends ApiObject {
    getHeight(): number {
        return callNum(607, this.handle, []);
    }

    getOffsetX(): number {
        return callNum(608, this.handle, []);
    }

    getOffsetY(): number {
        return callNum(609, this.handle, []);
    }

    getOriginalHeight(): number {
        return callNum(610, this.handle, []);
    }

    getOriginalWidth(): number {
        return callNum(611, this.handle, []);
    }

    getPalette(): ApiArray<number> {
        return new ApiArray<number>(callNum(612, this.handle, []), 'num', null);
    }

    getPixels(): ApiArray<number> {
        return new ApiArray<number>(callNum(613, this.handle, []), 'num', null);
    }

    getWidth(): number {
        return callNum(614, this.handle, []);
    }

    setHeight(a0: number): void {
        callVoid(615, this.handle, [a0]);
    }

    setOffsetX(a0: number): void {
        callVoid(616, this.handle, [a0]);
    }

    setOffsetY(a0: number): void {
        callVoid(617, this.handle, [a0]);
    }

    setOriginalHeight(a0: number): void {
        callVoid(618, this.handle, [a0]);
    }

    setOriginalWidth(a0: number): void {
        callVoid(619, this.handle, [a0]);
    }

    setWidth(a0: number): void {
        callVoid(620, this.handle, [a0]);
    }

}
