// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class InstanceTemplates extends ApiObject {
    getBaseX(): number {
        return callNum(621, this.handle, []);
    }

    getBaseY(): number {
        return callNum(622, this.handle, []);
    }

    getHeight(): number {
        return callNum(623, this.handle, []);
    }

    getPlane(): number {
        return callNum(624, this.handle, []);
    }

    getWidth(): number {
        return callNum(625, this.handle, []);
    }

    hashCode(): number {
        return callNum(626, this.handle, []);
    }

    name(): string | null {
        return callStr(627, this.handle, []);
    }

    ordinal(): number {
        return callNum(628, this.handle, []);
    }

    toString(): string | null {
        return callStr(629, this.handle, []);
    }

}
