// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callVoid, wrap } from './runtime';
import { Node } from './Node';

export class IntegerNode extends ApiObject {
    getHash(): number {
        return callNum(638, this.handle, []);
    }

    getNext(): Node | null {
        return wrap(639, this.handle, [], Node);
    }

    getPrevious(): Node | null {
        return wrap(640, this.handle, [], Node);
    }

    getValue(): number {
        return callNum(641, this.handle, []);
    }

    setValue(a0: number): void {
        callVoid(642, this.handle, [a0]);
    }

}
