// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Actor } from './Actor';

export class InteractingChanged extends ApiObject {
    getSource(): Actor | null {
        return wrap(1748, this.handle, [], Actor);
    }

    getTarget(): Actor | null {
        return wrap(1749, this.handle, [], Actor);
    }

    hashCode(): number {
        return callNum(1750, this.handle, []);
    }

    toString(): string | null {
        return callStr(1751, this.handle, []);
    }

}
