// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class InventoryID extends ApiObject {
    getId(): number {
        return callNum(643, this.handle, []);
    }

    hashCode(): number {
        return callNum(644, this.handle, []);
    }

    name(): string | null {
        return callStr(645, this.handle, []);
    }

    ordinal(): number {
        return callNum(646, this.handle, []);
    }

    toString(): string | null {
        return callStr(647, this.handle, []);
    }

}
