// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Tile } from './Tile';
import { TileItem } from './TileItem';

export class ItemQuantityChanged extends ApiObject {
    getItem(): TileItem | null {
        return wrap(1758, this.handle, [], TileItem);
    }

    getNewQuantity(): number {
        return callNum(1759, this.handle, []);
    }

    getOldQuantity(): number {
        return callNum(1760, this.handle, []);
    }

    getTile(): Tile | null {
        return wrap(1761, this.handle, [], Tile);
    }

    hashCode(): number {
        return callNum(1762, this.handle, []);
    }

    toString(): string | null {
        return callStr(1763, this.handle, []);
    }

}
