// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, wrap } from './runtime';
import { Item } from './Item';
import { Node } from './Node';

export class ItemContainer extends ApiObject {
    contains(a0: number): boolean {
        return callNum(689, this.handle, [a0]) !== 0;
    }

    count(): number {
        return callNum(690, this.handle, []);
    }

    count$int(a0: number): number {
        return callNum(691, this.handle, [a0]);
    }

    find(a0: number): number {
        return callNum(692, this.handle, [a0]);
    }

    getHash(): number {
        return callNum(693, this.handle, []);
    }

    getId(): number {
        return callNum(694, this.handle, []);
    }

    getItem(a0: number): Item | null {
        return wrap(695, this.handle, [a0], Item);
    }

    getItems(): ApiArray<Item | null> {
        return new ApiArray<Item | null>(callNum(696, this.handle, []), 'handle', Item);
    }

    getNext(): Node | null {
        return wrap(697, this.handle, [], Node);
    }

    getPrevious(): Node | null {
        return wrap(698, this.handle, [], Node);
    }

    size(): number {
        return callNum(699, this.handle, []);
    }

}
