// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Tile } from './Tile';
import { TileItem } from './TileItem';

export class ItemSpawned extends ApiObject {
    getItem(): TileItem | null {
        return wrap(1764, this.handle, [], TileItem);
    }

    getTile(): Tile | null {
        return wrap(1765, this.handle, [], Tile);
    }

    hashCode(): number {
        return callNum(1766, this.handle, []);
    }

    toString(): string | null {
        return callStr(1767, this.handle, []);
    }

}
