// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Tile } from './Tile';
import { TileItem } from './TileItem';

export class ItemDespawned extends ApiObject {
    getItem(): TileItem | null {
        return wrap(1754, this.handle, [], TileItem);
    }

    getTile(): Tile | null {
        return wrap(1755, this.handle, [], Tile);
    }

    hashCode(): number {
        return callNum(1756, this.handle, []);
    }

    toString(): string | null {
        return callStr(1757, this.handle, []);
    }

}
