// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { ItemContainer } from './ItemContainer';

export class ItemContainerChanged extends ApiObject {
    getContainerId(): number {
        return callNum(1750, this.handle, []);
    }

    getItemContainer(): ItemContainer | null {
        return wrap(1751, this.handle, [], ItemContainer);
    }

    hashCode(): number {
        return callNum(1752, this.handle, []);
    }

    toString(): string | null {
        return callStr(1753, this.handle, []);
    }

}
