// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class Item extends ApiObject {
    getId(): number {
        return callNum(648, this.handle, []);
    }

    getQuantity(): number {
        return callNum(649, this.handle, []);
    }

    hashCode(): number {
        return callNum(650, this.handle, []);
    }

    toString(): string | null {
        return callStr(651, this.handle, []);
    }

}
