// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callVoid, wrap } from './runtime';
import { Node } from './Node';

export class IterableHashTable extends ApiObject {
    get(a0: number): Node | null {
        return wrap(718, this.handle, [a0], Node);
    }

    put(a0: ApiObject | null, a1: number): void {
        callVoid(719, this.handle, [(a0 ? a0.handle : -1), a1]);
    }

}
