// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callVoid } from './runtime';

export class JavaScriptCallback extends ApiObject {
    run(a0: ApiObject | null): void {
        callVoid(1997, this.handle, [(a0 ? a0.handle : -1)]);
    }

}
