// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class KitType extends ApiObject {
    getIndex(): number {
        return callNum(1981, this.handle, []);
    }

    hashCode(): number {
        return callNum(1982, this.handle, []);
    }

    name(): string | null {
        return callStr(1983, this.handle, []);
    }

    ordinal(): number {
        return callNum(1984, this.handle, []);
    }

    toString(): string | null {
        return callStr(1985, this.handle, []);
    }

}
