// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';

export class LocalPoint extends ApiObject {
    distanceTo(a0: ApiObject | null): number {
        return callNum(1558, this.handle, [(a0 ? a0.handle : -1)]);
    }

    dx(a0: number): LocalPoint | null {
        return wrap(1559, this.handle, [a0], LocalPoint);
    }

    dy(a0: number): LocalPoint | null {
        return wrap(1560, this.handle, [a0], LocalPoint);
    }

    getSceneX(): number {
        return callNum(1561, this.handle, []);
    }

    getSceneY(): number {
        return callNum(1562, this.handle, []);
    }

    getWorldView(): number {
        return callNum(1563, this.handle, []);
    }

    getX(): number {
        return callNum(1564, this.handle, []);
    }

    getY(): number {
        return callNum(1565, this.handle, []);
    }

    hashCode(): number {
        return callNum(1566, this.handle, []);
    }

    isInScene(): boolean {
        return callNum(1567, this.handle, []) !== 0;
    }

    plus(a0: number, a1: number): LocalPoint | null {
        return wrap(1568, this.handle, [a0, a1], LocalPoint);
    }

    toString(): string | null {
        return callStr(1569, this.handle, []);
    }

}
