// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum } from './runtime';

export class MainBufferProvider extends ApiObject {
    getHeight(): number {
        return callNum(722, this.handle, []);
    }

    getPixels(): ApiArray<number> {
        return new ApiArray<number>(callNum(723, this.handle, []), 'num', null);
    }

    getWidth(): number {
        return callNum(724, this.handle, []);
    }

}
