// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, wrap } from './runtime';
import { SpritePixels } from './SpritePixels';

export class MapElementConfig extends ApiObject {
    getCategory(): number {
        return callNum(2155, this.handle, []);
    }

    getMapIcon(a0: boolean): SpritePixels | null {
        return wrap(2156, this.handle, [(a0 ? 1 : 0)], SpritePixels);
    }

}
