// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { MenuEntry } from './MenuEntry';

export class MenuEntryAdded extends ApiObject {
    getActionParam0(): number {
        return callNum(1768, this.handle, []);
    }

    getActionParam1(): number {
        return callNum(1769, this.handle, []);
    }

    getIdentifier(): number {
        return callNum(1770, this.handle, []);
    }

    getItemId(): number {
        return callNum(1771, this.handle, []);
    }

    getMenuEntry(): MenuEntry | null {
        return wrap(1772, this.handle, [], MenuEntry);
    }

    getOption(): string | null {
        return callStr(1773, this.handle, []);
    }

    getTarget(): string | null {
        return callStr(1774, this.handle, []);
    }

    getType(): number {
        return callNum(1775, this.handle, []);
    }

    hashCode(): number {
        return callNum(1776, this.handle, []);
    }

    toString(): string | null {
        return callStr(1777, this.handle, []);
    }

}
