// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class MenuAction extends ApiObject {
    getId(): number {
        return callNum(730, this.handle, []);
    }

    hashCode(): number {
        return callNum(731, this.handle, []);
    }

    name(): string | null {
        return callStr(732, this.handle, []);
    }

    ordinal(): number {
        return callNum(733, this.handle, []);
    }

    toString(): string | null {
        return callStr(734, this.handle, []);
    }

}
