// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callStr, wrap } from './runtime';
import { MenuEntry } from './MenuEntry';

export class MenuOpened extends ApiObject {
    getFirstEntry(): MenuEntry | null {
        return wrap(1778, this.handle, [], MenuEntry);
    }

    getMenuEntries(): ApiArray<MenuEntry | null> {
        return new ApiArray<MenuEntry | null>(callNum(1779, this.handle, []), 'handle', MenuEntry);
    }

    hashCode(): number {
        return callNum(1780, this.handle, []);
    }

    toString(): string | null {
        return callStr(1781, this.handle, []);
    }

}
