// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum } from './runtime';

export class MidiRequest extends ApiObject {
    getArchiveId(): number {
        return callNum(793, this.handle, []);
    }

    isJingle(): boolean {
        return callNum(794, this.handle, []) !== 0;
    }

}
