// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callVoid, wrap } from './runtime';
import { Mesh } from './Mesh';
import { Model } from './Model';
import { Node } from './Node';

export class ModelData extends ApiObject {
    cloneColors(): ModelData | null {
        return wrap(853, this.handle, [], ModelData);
    }

    cloneTextures(): ModelData | null {
        return wrap(854, this.handle, [], ModelData);
    }

    cloneTransparencies(): ModelData | null {
        return wrap(855, this.handle, [], ModelData);
    }

    cloneTransparencies$boolean(a0: boolean): ModelData | null {
        return wrap(856, this.handle, [(a0 ? 1 : 0)], ModelData);
    }

    cloneVertices(): ModelData | null {
        return wrap(857, this.handle, [], ModelData);
    }

    getAnimationHeightOffset(): number {
        return callNum(858, this.handle, []);
    }

    getFaceColors(): ApiArray<number> {
        return new ApiArray<number>(callNum(859, this.handle, []), 'num', null);
    }

    getFaceCount(): number {
        return callNum(860, this.handle, []);
    }

    getFaceIndices1(): ApiArray<number> {
        return new ApiArray<number>(callNum(861, this.handle, []), 'num', null);
    }

    getFaceIndices2(): ApiArray<number> {
        return new ApiArray<number>(callNum(862, this.handle, []), 'num', null);
    }

    getFaceIndices3(): ApiArray<number> {
        return new ApiArray<number>(callNum(863, this.handle, []), 'num', null);
    }

    getFaceTextures(): ApiArray<number> {
        return new ApiArray<number>(callNum(864, this.handle, []), 'num', null);
    }

    getFaceTransparencies(): ApiArray<number> {
        return new ApiArray<number>(callNum(865, this.handle, []), 'num', null);
    }

    getHash(): number {
        return callNum(866, this.handle, []);
    }

    getModel(): Model | null {
        return wrap(867, this.handle, [], Model);
    }

    getModelHeight(): number {
        return callNum(868, this.handle, []);
    }

    getNext(): Node | null {
        return wrap(869, this.handle, [], Node);
    }

    getPrevious(): Node | null {
        return wrap(870, this.handle, [], Node);
    }

    getRenderMode(): number {
        return callNum(871, this.handle, []);
    }

    getVerticesCount(): number {
        return callNum(872, this.handle, []);
    }

    getVerticesX(): ApiArray<number> {
        return new ApiArray<number>(callNum(873, this.handle, []), 'num', null);
    }

    getVerticesY(): ApiArray<number> {
        return new ApiArray<number>(callNum(874, this.handle, []), 'num', null);
    }

    getVerticesZ(): ApiArray<number> {
        return new ApiArray<number>(callNum(875, this.handle, []), 'num', null);
    }

    light(): Model | null {
        return wrap(876, this.handle, [], Model);
    }

    recolor(a0: number, a1: number): ModelData | null {
        return wrap(877, this.handle, [a0, a1], ModelData);
    }

    retexture(a0: number, a1: number): ModelData | null {
        return wrap(878, this.handle, [a0, a1], ModelData);
    }

    rotateY180Ccw(): Mesh | null {
        return wrap(879, this.handle, [], Mesh);
    }

    rotateY270Ccw(): Mesh | null {
        return wrap(880, this.handle, [], Mesh);
    }

    rotateY90Ccw(): Mesh | null {
        return wrap(881, this.handle, [], Mesh);
    }

    scale(a0: number, a1: number, a2: number): Mesh | null {
        return wrap(882, this.handle, [a0, a1, a2], Mesh);
    }

    setModelHeight(a0: number): void {
        callVoid(883, this.handle, [a0]);
    }

    shallowCopy(): ModelData | null {
        return wrap(884, this.handle, [], ModelData);
    }

    translate(a0: number, a1: number, a2: number): Mesh | null {
        return wrap(885, this.handle, [a0, a1, a2], Mesh);
    }

}
