// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Nameable } from './Nameable';

export class NameableNameChanged extends ApiObject {
    getNameable(): Nameable | null {
        return wrap(1805, this.handle, [], Nameable);
    }

    hashCode(): number {
        return callNum(1806, this.handle, []);
    }

    toString(): string | null {
        return callStr(1807, this.handle, []);
    }

}
