// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callStrArg, wrap } from './runtime';
import { Nameable } from './Nameable';

export class NameableContainer extends ApiObject {
    findByName(a0: string): Nameable | null {
        callStrArg(0, a0);
        return wrap(989, this.handle, [0], Nameable);
    }

    getCount(): number {
        return callNum(990, this.handle, []);
    }

    getMembers(): ApiArray<Nameable | null> {
        return new ApiArray<Nameable | null>(callNum(991, this.handle, []), 'handle', Nameable);
    }

    getSize(): number {
        return callNum(992, this.handle, []);
    }

}
