// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callStr } from './runtime';

export class Nameable extends ApiObject {
    getName(): string | null {
        return callStr(985, this.handle, []);
    }

    getPrevName(): string | null {
        return callStr(986, this.handle, []);
    }

}
