// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, wrap } from './runtime';

export class Node extends ApiObject {
    getHash(): number {
        return callNum(993, this.handle, []);
    }

    getNext(): Node | null {
        return wrap(994, this.handle, [], Node);
    }

    getPrevious(): Node | null {
        return wrap(995, this.handle, [], Node);
    }

}
