// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callVoid } from './runtime';

export class NodeCache extends ApiObject {
    reset(): void {
        callVoid(994, this.handle, []);
    }

}
