// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callStr, callStrArg, callVoid, wrap } from './runtime';
import { EntityOps } from './EntityOps';
import { IterableHashTable } from './IterableHashTable';

export class NPCComposition extends ApiObject {
    getActions(): ApiArray<string | null> {
        return new ApiArray<string | null>(callNum(961, this.handle, []), 'str', null);
    }

    getChatheadModels(): ApiArray<number> {
        return new ApiArray<number>(callNum(962, this.handle, []), 'num', null);
    }

    getColorToReplace(): ApiArray<number> {
        return new ApiArray<number>(callNum(963, this.handle, []), 'num', null);
    }

    getColorToReplaceWith(): ApiArray<number> {
        return new ApiArray<number>(callNum(964, this.handle, []), 'num', null);
    }

    getCombatLevel(): number {
        return callNum(965, this.handle, []);
    }

    getConfigs(): ApiArray<number> {
        return new ApiArray<number>(callNum(966, this.handle, []), 'num', null);
    }

    getFootprintSize(): number {
        return callNum(967, this.handle, []);
    }

    getHeightScale(): number {
        return callNum(968, this.handle, []);
    }

    getId(): number {
        return callNum(969, this.handle, []);
    }

    getIntValue(a0: number): number {
        return callNum(970, this.handle, [a0]);
    }

    getLongValue(a0: number): number {
        return callNum(971, this.handle, [a0]);
    }

    getModels(): ApiArray<number> {
        return new ApiArray<number>(callNum(972, this.handle, []), 'num', null);
    }

    getName(): string | null {
        return callStr(973, this.handle, []);
    }

    getOps(): EntityOps | null {
        return wrap(974, this.handle, [], EntityOps);
    }

    getParams(): IterableHashTable | null {
        return wrap(975, this.handle, [], IterableHashTable);
    }

    getSize(): number {
        return callNum(976, this.handle, []);
    }

    getStats(): ApiArray<number> {
        return new ApiArray<number>(callNum(977, this.handle, []), 'num', null);
    }

    getStringValue(a0: number): string | null {
        return callStr(978, this.handle, [a0]);
    }

    getWidthScale(): number {
        return callNum(979, this.handle, []);
    }

    isFollower(): boolean {
        return callNum(980, this.handle, []) !== 0;
    }

    isInteractible(): boolean {
        return callNum(981, this.handle, []) !== 0;
    }

    isMinimapVisible(): boolean {
        return callNum(982, this.handle, []) !== 0;
    }

    setValue(a0: number, a1: number): void {
        callVoid(983, this.handle, [a0, a1]);
    }

    setValue$int_String(a0: number, a1: string): void {
        callStrArg(1, a1);
        callVoid(984, this.handle, [a0, 0]);
    }

    setValue$int_long(a0: number, a1: number): void {
        callVoid(985, this.handle, [a0, a1]);
    }

    transform(): NPCComposition | null {
        return wrap(986, this.handle, [], NPCComposition);
    }

}
