// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { NPC } from './NPC';
import { NPCComposition } from './NPCComposition';

export class NpcChanged extends ApiObject {
    getNpc(): NPC | null {
        return wrap(1808, this.handle, [], NPC);
    }

    getOld(): NPCComposition | null {
        return wrap(1809, this.handle, [], NPCComposition);
    }

    hashCode(): number {
        return callNum(1810, this.handle, []);
    }

    toString(): string | null {
        return callStr(1811, this.handle, []);
    }

}
