// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Actor } from './Actor';
import { NPC } from './NPC';

export class NpcSpawned extends ApiObject {
    getActor(): Actor | null {
        return wrap(1816, this.handle, [], Actor);
    }

    getNpc(): NPC | null {
        return wrap(1817, this.handle, [], NPC);
    }

    hashCode(): number {
        return callNum(1818, this.handle, []);
    }

    toString(): string | null {
        return callStr(1819, this.handle, []);
    }

}
