// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callStr, callStrArg, callVoid, wrap } from './runtime';
import { EntityOps } from './EntityOps';
import { IterableHashTable } from './IterableHashTable';

export class ObjectComposition extends ApiObject {
    getActions(): ApiArray<string | null> {
        return new ApiArray<string | null>(callNum(999, this.handle, []), 'str', null);
    }

    getAnimationId(): number {
        return callNum(1000, this.handle, []);
    }

    getId(): number {
        return callNum(1001, this.handle, []);
    }

    getImpostor(): ObjectComposition | null {
        return wrap(1002, this.handle, [], ObjectComposition);
    }

    getImpostorIds(): ApiArray<number> {
        return new ApiArray<number>(callNum(1003, this.handle, []), 'num', null);
    }

    getIntValue(a0: number): number {
        return callNum(1004, this.handle, [a0]);
    }

    getLongValue(a0: number): number {
        return callNum(1005, this.handle, [a0]);
    }

    getMapIconId(): number {
        return callNum(1006, this.handle, []);
    }

    getMapSceneId(): number {
        return callNum(1007, this.handle, []);
    }

    getName(): string | null {
        return callStr(1008, this.handle, []);
    }

    getOps(): EntityOps | null {
        return wrap(1009, this.handle, [], EntityOps);
    }

    getParams(): IterableHashTable | null {
        return wrap(1010, this.handle, [], IterableHashTable);
    }

    getSizeX(): number {
        return callNum(1011, this.handle, []);
    }

    getSizeY(): number {
        return callNum(1012, this.handle, []);
    }

    getStringValue(a0: number): string | null {
        return callStr(1013, this.handle, [a0]);
    }

    getVarPlayerId(): number {
        return callNum(1014, this.handle, []);
    }

    getVarbitId(): number {
        return callNum(1015, this.handle, []);
    }

    setAnimationId(a0: number): void {
        callVoid(1016, this.handle, [a0]);
    }

    setMapIconId(a0: number): void {
        callVoid(1017, this.handle, [a0]);
    }

    setMapSceneId(a0: number): void {
        callVoid(1018, this.handle, [a0]);
    }

    setValue(a0: number, a1: number): void {
        callVoid(1019, this.handle, [a0, a1]);
    }

    setValue$int_String(a0: number, a1: string): void {
        callStrArg(1, a1);
        callVoid(1020, this.handle, [a0, 0]);
    }

    setValue$int_long(a0: number, a1: number): void {
        callVoid(1021, this.handle, [a0, a1]);
    }

}
