// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Actor } from './Actor';

export class OverheadTextChanged extends ApiObject {
    getActor(): Actor | null {
        return wrap(1820, this.handle, [], Actor);
    }

    getOverheadText(): string | null {
        return callStr(1821, this.handle, []);
    }

    hashCode(): number {
        return callNum(1822, this.handle, []);
    }

    toString(): string | null {
        return callStr(1823, this.handle, []);
    }

}
