// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class PendingLogin extends ApiObject {
    getName(): string | null {
        return callStr(1027, this.handle, []);
    }

    getWorld(): number {
        return callNum(1028, this.handle, []);
    }

}
