// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid } from './runtime';

export class PlayerMenuOptionsChanged extends ApiObject {
    getIndex(): number {
        return callNum(1829, this.handle, []);
    }

    hashCode(): number {
        return callNum(1830, this.handle, []);
    }

    setIndex(a0: number): void {
        callVoid(1831, this.handle, [a0]);
    }

    toString(): string | null {
        return callStr(1832, this.handle, []);
    }

}
