// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Player } from './Player';

export class PlayerChanged extends ApiObject {
    getPlayer(): Player | null {
        return wrap(1824, this.handle, [], Player);
    }

    hashCode(): number {
        return callNum(1825, this.handle, []);
    }

    toString(): string | null {
        return callStr(1826, this.handle, []);
    }

}
