// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Actor } from './Actor';
import { Player } from './Player';

export class PlayerSpawned extends ApiObject {
    getActor(): Actor | null {
        return wrap(1835, this.handle, [], Actor);
    }

    getPlayer(): Player | null {
        return wrap(1836, this.handle, [], Player);
    }

    hashCode(): number {
        return callNum(1837, this.handle, []);
    }

    toString(): string | null {
        return callStr(1838, this.handle, []);
    }

}
