// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callVoid } from './runtime';
import { ColorTextureOverride } from './ColorTextureOverride';

export class PlayerComposition extends ApiObject {
    getColorTextureOverrides(): ApiArray<ColorTextureOverride | null> {
        return new ApiArray<ColorTextureOverride | null>(callNum(1107, this.handle, []), 'handle', ColorTextureOverride);
    }

    getColors(): ApiArray<number> {
        return new ApiArray<number>(callNum(1108, this.handle, []), 'num', null);
    }

    getEquipmentIds(): ApiArray<number> {
        return new ApiArray<number>(callNum(1109, this.handle, []), 'num', null);
    }

    getGender(): number {
        return callNum(1110, this.handle, []);
    }

    getTransformedNpcId(): number {
        return callNum(1111, this.handle, []);
    }

    isFemale(): boolean {
        return callNum(1112, this.handle, []) !== 0;
    }

    setHash(): void {
        callVoid(1113, this.handle, []);
    }

    setTransformedNpcId(a0: number): void {
        callVoid(1114, this.handle, [a0]);
    }

}
