// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Actor } from './Actor';
import { Player } from './Player';

export class PlayerDespawned extends ApiObject {
    getActor(): Actor | null {
        return wrap(1825, this.handle, [], Actor);
    }

    getPlayer(): Player | null {
        return wrap(1826, this.handle, [], Player);
    }

    hashCode(): number {
        return callNum(1827, this.handle, []);
    }

    toString(): string | null {
        return callStr(1828, this.handle, []);
    }

}
