// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class Point extends ApiObject {
    distanceTo(a0: ApiObject | null): number {
        return callNum(1115, this.handle, [(a0 ? a0.handle : -1)]);
    }

    getX(): number {
        return callNum(1116, this.handle, []);
    }

    getY(): number {
        return callNum(1117, this.handle, []);
    }

    hashCode(): number {
        return callNum(1118, this.handle, []);
    }

    toString(): string | null {
        return callStr(1119, this.handle, []);
    }

}
