// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { ItemComposition } from './ItemComposition';

export class PostItemComposition extends ApiObject {
    getItemComposition(): ItemComposition | null {
        return wrap(1846, this.handle, [], ItemComposition);
    }

    hashCode(): number {
        return callNum(1847, this.handle, []);
    }

    toString(): string | null {
        return callStr(1848, this.handle, []);
    }

}
