// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { HealthBarConfig } from './HealthBarConfig';

export class PostHealthBarConfig extends ApiObject {
    getHealthBarConfig(): HealthBarConfig | null {
        return wrap(1842, this.handle, [], HealthBarConfig);
    }

    hashCode(): number {
        return callNum(1843, this.handle, []);
    }

    setHealthBarConfig(a0: ApiObject | null): void {
        callVoid(1844, this.handle, [(a0 ? a0.handle : -1)]);
    }

    toString(): string | null {
        return callStr(1845, this.handle, []);
    }

}
