// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { StructComposition } from './StructComposition';

export class PostStructComposition extends ApiObject {
    getStructComposition(): StructComposition | null {
        return wrap(1850, this.handle, [], StructComposition);
    }

    hashCode(): number {
        return callNum(1851, this.handle, []);
    }

    setStructComposition(a0: ApiObject | null): void {
        callVoid(1852, this.handle, [(a0 ? a0.handle : -1)]);
    }

    toString(): string | null {
        return callStr(1853, this.handle, []);
    }

}
