// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Animation } from './Animation';

export class PostAnimation extends ApiObject {
    getAnimation(): Animation | null {
        return wrap(1837, this.handle, [], Animation);
    }

    hashCode(): number {
        return callNum(1838, this.handle, []);
    }

    toString(): string | null {
        return callStr(1839, this.handle, []);
    }

}
