// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { ObjectComposition } from './ObjectComposition';

export class PostObjectComposition extends ApiObject {
    getObjectComposition(): ObjectComposition | null {
        return wrap(1847, this.handle, [], ObjectComposition);
    }

    hashCode(): number {
        return callNum(1848, this.handle, []);
    }

    toString(): string | null {
        return callStr(1849, this.handle, []);
    }

}
