// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class Prayer extends ApiObject {
    getVarbit(): number {
        return callNum(1118, this.handle, []);
    }

    hashCode(): number {
        return callNum(1119, this.handle, []);
    }

    name(): string | null {
        return callStr(1120, this.handle, []);
    }

    ordinal(): number {
        return callNum(1121, this.handle, []);
    }

    toString(): string | null {
        return callStr(1122, this.handle, []);
    }

}
