// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Scene } from './Scene';
import { WorldView } from './WorldView';

export class PreMapLoad extends ApiObject {
    getScene(): Scene | null {
        return wrap(1854, this.handle, [], Scene);
    }

    getWorldView(): WorldView | null {
        return wrap(1855, this.handle, [], WorldView);
    }

    hashCode(): number {
        return callNum(1856, this.handle, []);
    }

    toString(): string | null {
        return callStr(1857, this.handle, []);
    }

}
