// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { LocalPoint } from './LocalPoint';
import { Projectile } from './Projectile';

export class ProjectileMoved extends ApiObject {
    getPosition(): LocalPoint | null {
        return wrap(1858, this.handle, [], LocalPoint);
    }

    getProjectile(): Projectile | null {
        return wrap(1859, this.handle, [], Projectile);
    }

    getZ(): number {
        return callNum(1860, this.handle, []);
    }

    hashCode(): number {
        return callNum(1861, this.handle, []);
    }

    setPosition(a0: ApiObject | null): void {
        callVoid(1862, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setProjectile(a0: ApiObject | null): void {
        callVoid(1863, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setZ(a0: number): void {
        callVoid(1864, this.handle, [a0]);
    }

    toString(): string | null {
        return callStr(1865, this.handle, []);
    }

}
