// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class QuestState extends ApiObject {
    hashCode(): number {
        return callNum(1175, this.handle, []);
    }

    name(): string | null {
        return callStr(1176, this.handle, []);
    }

    ordinal(): number {
        return callNum(1177, this.handle, []);
    }

    toString(): string | null {
        return callStr(1178, this.handle, []);
    }

}
