// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Nameable } from './Nameable';

export class RemovedFriend extends ApiObject {
    getNameable(): Nameable | null {
        return wrap(1866, this.handle, [], Nameable);
    }

    hashCode(): number {
        return callNum(1867, this.handle, []);
    }

    toString(): string | null {
        return callStr(1868, this.handle, []);
    }

}
