// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid } from './runtime';

export class ResizeableChanged extends ApiObject {
    hashCode(): number {
        return callNum(1869, this.handle, []);
    }

    isResized(): boolean {
        return callNum(1870, this.handle, []) !== 0;
    }

    setResized(a0: boolean): void {
        callVoid(1871, this.handle, [(a0 ? 1 : 0)]);
    }

    toString(): string | null {
        return callStr(1872, this.handle, []);
    }

}
