// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class ScriptPostFired extends ApiObject {
    getScriptId(): number {
        return callNum(1879, this.handle, []);
    }

    hashCode(): number {
        return callNum(1880, this.handle, []);
    }

    toString(): string | null {
        return callStr(1881, this.handle, []);
    }

}
