// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, wrap } from './runtime';
import { ScriptEvent } from './ScriptEvent';
import { Widget } from './Widget';

export class ScriptEventBuilder extends ApiObject {
    build(): ScriptEvent | null {
        return wrap(1349, this.handle, [], ScriptEvent);
    }

    getArguments(): ApiArray<number> {
        return new ApiArray<number>(callNum(1350, this.handle, []), 'none', null);
    }

    getOp(): number {
        return callNum(1351, this.handle, []);
    }

    getSource(): Widget | null {
        return wrap(1352, this.handle, [], Widget);
    }

    getTarget(): Widget | null {
        return wrap(1353, this.handle, [], Widget);
    }

    setOp(a0: number): ScriptEventBuilder | null {
        return wrap(1354, this.handle, [a0], ScriptEventBuilder);
    }

    setSource(a0: ApiObject | null): ScriptEventBuilder | null {
        return wrap(1355, this.handle, [(a0 ? a0.handle : -1)], ScriptEventBuilder);
    }

    setTarget(a0: ApiObject | null): ScriptEventBuilder | null {
        return wrap(1356, this.handle, [(a0 ? a0.handle : -1)], ScriptEventBuilder);
    }

}
