// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class Skill extends ApiObject {
    getName(): string | null {
        return callStr(1357, this.handle, []);
    }

    hashCode(): number {
        return callNum(1358, this.handle, []);
    }

    isMembers(): boolean {
        return callNum(1359, this.handle, []) !== 0;
    }

    name(): string | null {
        return callStr(1360, this.handle, []);
    }

    ordinal(): number {
        return callNum(1361, this.handle, []);
    }

    toString(): string | null {
        return callStr(1362, this.handle, []);
    }

}
