// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { Actor } from './Actor';

export class SoundEffectPlayed extends ApiObject {
    consume(): void {
        callVoid(1889, this.handle, []);
    }

    getDelay(): number {
        return callNum(1890, this.handle, []);
    }

    getSoundId(): number {
        return callNum(1891, this.handle, []);
    }

    getSource(): Actor | null {
        return wrap(1892, this.handle, [], Actor);
    }

    hashCode(): number {
        return callNum(1893, this.handle, []);
    }

    isConsumed(): boolean {
        return callNum(1894, this.handle, []) !== 0;
    }

    setConsumed(a0: boolean): void {
        callVoid(1895, this.handle, [(a0 ? 1 : 0)]);
    }

    setDelay(a0: number): void {
        callVoid(1896, this.handle, [a0]);
    }

    setSoundId(a0: number): void {
        callVoid(1897, this.handle, [a0]);
    }

    toString(): string | null {
        return callStr(1898, this.handle, []);
    }

}
