// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callVoid, wrap } from './runtime';
import { Model } from './Model';
import { Node } from './Node';

export class TileItem extends ApiObject {
    getAnimationHeightOffset(): number {
        return callNum(1418, this.handle, []);
    }

    getDespawnTime(): number {
        return callNum(1419, this.handle, []);
    }

    getHash(): number {
        return callNum(1420, this.handle, []);
    }

    getId(): number {
        return callNum(1421, this.handle, []);
    }

    getModel(): Model | null {
        return wrap(1422, this.handle, [], Model);
    }

    getModelHeight(): number {
        return callNum(1423, this.handle, []);
    }

    getNext(): Node | null {
        return wrap(1424, this.handle, [], Node);
    }

    getOwnership(): number {
        return callNum(1425, this.handle, []);
    }

    getPrevious(): Node | null {
        return wrap(1426, this.handle, [], Node);
    }

    getQuantity(): number {
        return callNum(1427, this.handle, []);
    }

    getRenderMode(): number {
        return callNum(1428, this.handle, []);
    }

    getVisibleTime(): number {
        return callNum(1429, this.handle, []);
    }

    isPrivate(): boolean {
        return callNum(1430, this.handle, []) !== 0;
    }

    setModelHeight(a0: number): void {
        callVoid(1431, this.handle, [a0]);
    }

}
