// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { LocalPoint } from './LocalPoint';
import { Point } from './Point';
import { WorldPoint } from './WorldPoint';
import { WorldView } from './WorldView';

export class TileObject extends ApiObject {
    getCanvasLocation(): Point | null {
        return wrap(1430, this.handle, [], Point);
    }

    getCanvasLocation$int(a0: number): Point | null {
        return wrap(1431, this.handle, [a0], Point);
    }

    getHash(): number {
        return callNum(1432, this.handle, []);
    }

    getId(): number {
        return callNum(1433, this.handle, []);
    }

    getLocalLocation(): LocalPoint | null {
        return wrap(1434, this.handle, [], LocalPoint);
    }

    getMinimapLocation(): Point | null {
        return wrap(1435, this.handle, [], Point);
    }

    getOpOverride(a0: number): string | null {
        return callStr(1436, this.handle, [a0]);
    }

    getPlane(): number {
        return callNum(1437, this.handle, []);
    }

    getWorldLocation(): WorldPoint | null {
        return wrap(1438, this.handle, [], WorldPoint);
    }

    getWorldView(): WorldView | null {
        return wrap(1439, this.handle, [], WorldView);
    }

    getX(): number {
        return callNum(1440, this.handle, []);
    }

    getY(): number {
        return callNum(1441, this.handle, []);
    }

    getZ(): number {
        return callNum(1442, this.handle, []);
    }

    isOpShown(a0: number): boolean {
        return callNum(1443, this.handle, [a0]) !== 0;
    }

}
