// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callVoid, wrap } from './runtime';
import { DecorativeObject } from './DecorativeObject';
import { GameObject } from './GameObject';
import { GroundObject } from './GroundObject';
import { ItemLayer } from './ItemLayer';
import { LocalPoint } from './LocalPoint';
import { Point } from './Point';
import { SceneTileModel } from './SceneTileModel';
import { SceneTilePaint } from './SceneTilePaint';
import { WallObject } from './WallObject';
import { WorldPoint } from './WorldPoint';

export class Tile extends ApiObject {
    getBridge(): Tile | null {
        return wrap(1400, this.handle, [], Tile);
    }

    getDecorativeObject(): DecorativeObject | null {
        return wrap(1401, this.handle, [], DecorativeObject);
    }

    getGameObjects(): ApiArray<GameObject | null> {
        return new ApiArray<GameObject | null>(callNum(1402, this.handle, []), 'handle', GameObject);
    }

    getGroundObject(): GroundObject | null {
        return wrap(1403, this.handle, [], GroundObject);
    }

    getItemLayer(): ItemLayer | null {
        return wrap(1404, this.handle, [], ItemLayer);
    }

    getLocalLocation(): LocalPoint | null {
        return wrap(1405, this.handle, [], LocalPoint);
    }

    getPlane(): number {
        return callNum(1406, this.handle, []);
    }

    getRenderLevel(): number {
        return callNum(1407, this.handle, []);
    }

    getSceneLocation(): Point | null {
        return wrap(1408, this.handle, [], Point);
    }

    getSceneTileModel(): SceneTileModel | null {
        return wrap(1409, this.handle, [], SceneTileModel);
    }

    getSceneTilePaint(): SceneTilePaint | null {
        return wrap(1410, this.handle, [], SceneTilePaint);
    }

    getWallObject(): WallObject | null {
        return wrap(1411, this.handle, [], WallObject);
    }

    getWorldLocation(): WorldPoint | null {
        return wrap(1412, this.handle, [], WorldPoint);
    }

    setGroundObject(a0: ApiObject | null): void {
        callVoid(1413, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setSceneTileModel(a0: ApiObject | null): void {
        callVoid(1414, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setSceneTilePaint(a0: ApiObject | null): void {
        callVoid(1415, this.handle, [(a0 ? a0.handle : -1)]);
    }

}
