// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum } from './runtime';

export class VarbitComposition extends ApiObject {
    getIndex(): number {
        return callNum(1444, this.handle, []);
    }

    getLeastSignificantBit(): number {
        return callNum(1445, this.handle, []);
    }

    getMostSignificantBit(): number {
        return callNum(1446, this.handle, []);
    }

}
