// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class VarClientIntChanged extends ApiObject {
    getIndex(): number {
        return callNum(1903, this.handle, []);
    }

    hashCode(): number {
        return callNum(1904, this.handle, []);
    }

    toString(): string | null {
        return callStr(1905, this.handle, []);
    }

}
