// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class VarClientStrChanged extends ApiObject {
    getIndex(): number {
        return callNum(1908, this.handle, []);
    }

    hashCode(): number {
        return callNum(1909, this.handle, []);
    }

    toString(): string | null {
        return callStr(1910, this.handle, []);
    }

}
