// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class VolumeChanged extends ApiObject {
    getType(): string | null {
        return callStr(1920, this.handle, []);
    }

    hashCode(): number {
        return callNum(1921, this.handle, []);
    }

    toString(): string | null {
        return callStr(1922, this.handle, []);
    }

}
