// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid, wrap } from './runtime';
import { Tile } from './Tile';
import { WallObject } from './WallObject';

export class WallObjectSpawned extends ApiObject {
    getTile(): Tile | null {
        return wrap(1929, this.handle, [], Tile);
    }

    getWallObject(): WallObject | null {
        return wrap(1930, this.handle, [], WallObject);
    }

    hashCode(): number {
        return callNum(1931, this.handle, []);
    }

    setTile(a0: ApiObject | null): void {
        callVoid(1932, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setWallObject(a0: ApiObject | null): void {
        callVoid(1933, this.handle, [(a0 ? a0.handle : -1)]);
    }

    toString(): string | null {
        return callStr(1934, this.handle, []);
    }

}
