// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { LocalPoint } from './LocalPoint';
import { Point } from './Point';
import { Renderable } from './Renderable';
import { WorldPoint } from './WorldPoint';
import { WorldView } from './WorldView';

export class WallObject extends ApiObject {
    getCanvasLocation(): Point | null {
        return wrap(1449, this.handle, [], Point);
    }

    getCanvasLocation$int(a0: number): Point | null {
        return wrap(1450, this.handle, [a0], Point);
    }

    getConfig(): number {
        return callNum(1451, this.handle, []);
    }

    getHash(): number {
        return callNum(1452, this.handle, []);
    }

    getId(): number {
        return callNum(1453, this.handle, []);
    }

    getLocalLocation(): LocalPoint | null {
        return wrap(1454, this.handle, [], LocalPoint);
    }

    getMinimapLocation(): Point | null {
        return wrap(1455, this.handle, [], Point);
    }

    getOpOverride(a0: number): string | null {
        return callStr(1456, this.handle, [a0]);
    }

    getOrientationA(): number {
        return callNum(1457, this.handle, []);
    }

    getOrientationB(): number {
        return callNum(1458, this.handle, []);
    }

    getPlane(): number {
        return callNum(1459, this.handle, []);
    }

    getRenderable1(): Renderable | null {
        return wrap(1460, this.handle, [], Renderable);
    }

    getRenderable2(): Renderable | null {
        return wrap(1461, this.handle, [], Renderable);
    }

    getWorldLocation(): WorldPoint | null {
        return wrap(1462, this.handle, [], WorldPoint);
    }

    getWorldView(): WorldView | null {
        return wrap(1463, this.handle, [], WorldView);
    }

    getX(): number {
        return callNum(1464, this.handle, []);
    }

    getY(): number {
        return callNum(1465, this.handle, []);
    }

    getZ(): number {
        return callNum(1466, this.handle, []);
    }

    isOpShown(a0: number): boolean {
        return callNum(1467, this.handle, [a0]) !== 0;
    }

}
