// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, wrap } from './runtime';
import { Node } from './Node';

export class WidgetConfigNode extends ApiObject {
    getClickMask(): number {
        return callNum(2137, this.handle, []);
    }

    getHash(): number {
        return callNum(2138, this.handle, []);
    }

    getNext(): Node | null {
        return wrap(2139, this.handle, [], Node);
    }

    getOpMask(): number {
        return callNum(2140, this.handle, []);
    }

    getPrevious(): Node | null {
        return wrap(2141, this.handle, [], Node);
    }

}
