// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, callVoid } from './runtime';

export class WidgetLoaded extends ApiObject {
    getGroupId(): number {
        return callNum(1938, this.handle, []);
    }

    hashCode(): number {
        return callNum(1939, this.handle, []);
    }

    setGroupId(a0: number): void {
        callVoid(1940, this.handle, [a0]);
    }

    toString(): string | null {
        return callStr(1941, this.handle, []);
    }

}
