// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callStr, callStrArg, callVoid, wrap } from './runtime';
import { FontTypeFace } from './FontTypeFace';
import { Point } from './Point';

export class Widget extends ApiObject {
    clearActions(): void {
        callVoid(1996, this.handle, []);
    }

    contains(a0: ApiObject | null): boolean {
        return callNum(1997, this.handle, [(a0 ? a0.handle : -1)]) !== 0;
    }

    createChild(a0: number): Widget | null {
        return wrap(1998, this.handle, [a0], Widget);
    }

    createChild$int_int(a0: number, a1: number): Widget | null {
        return wrap(1999, this.handle, [a0, a1], Widget);
    }

    deleteAllChildren(): void {
        callVoid(2000, this.handle, []);
    }

    getActions(): ApiArray<string | null> {
        return new ApiArray<string | null>(callNum(2001, this.handle, []), 'str', null);
    }

    getAnimationId(): number {
        return callNum(2002, this.handle, []);
    }

    getBorderType(): number {
        return callNum(2003, this.handle, []);
    }

    getCanvasLocation(): Point | null {
        return wrap(2004, this.handle, [], Point);
    }

    getChild(a0: number): Widget | null {
        return wrap(2005, this.handle, [a0], Widget);
    }

    getChildren(): ApiArray<Widget | null> {
        return new ApiArray<Widget | null>(callNum(2006, this.handle, []), 'handle', Widget);
    }

    getClickMask(): number {
        return callNum(2007, this.handle, []);
    }

    getContentType(): number {
        return callNum(2008, this.handle, []);
    }

    getDragDeadTime(): number {
        return callNum(2009, this.handle, []);
    }

    getDragDeadZone(): number {
        return callNum(2010, this.handle, []);
    }

    getDragParent(): Widget | null {
        return wrap(2011, this.handle, [], Widget);
    }

    getDynamicChildren(): ApiArray<Widget | null> {
        return new ApiArray<Widget | null>(callNum(2012, this.handle, []), 'handle', Widget);
    }

    getFont(): FontTypeFace | null {
        return wrap(2013, this.handle, [], FontTypeFace);
    }

    getFontId(): number {
        return callNum(2014, this.handle, []);
    }

    getHeight(): number {
        return callNum(2015, this.handle, []);
    }

    getHeightMode(): number {
        return callNum(2016, this.handle, []);
    }

    getId(): number {
        return callNum(2017, this.handle, []);
    }

    getIndex(): number {
        return callNum(2018, this.handle, []);
    }

    getItemId(): number {
        return callNum(2019, this.handle, []);
    }

    getItemQuantity(): number {
        return callNum(2020, this.handle, []);
    }

    getItemQuantityMode(): number {
        return callNum(2021, this.handle, []);
    }

    getLineHeight(): number {
        return callNum(2022, this.handle, []);
    }

    getModelId(): number {
        return callNum(2023, this.handle, []);
    }

    getModelType(): number {
        return callNum(2024, this.handle, []);
    }

    getModelZoom(): number {
        return callNum(2025, this.handle, []);
    }

    getName(): string | null {
        return callStr(2026, this.handle, []);
    }

    getNestedChildren(): ApiArray<Widget | null> {
        return new ApiArray<Widget | null>(callNum(2027, this.handle, []), 'handle', Widget);
    }

    getNoClickThrough(): boolean {
        return callNum(2028, this.handle, []) !== 0;
    }

    getNoScrollThrough(): boolean {
        return callNum(2029, this.handle, []) !== 0;
    }

    getOnInvTransmitListener(): ApiArray<number> {
        return new ApiArray<number>(callNum(2030, this.handle, []), 'none', null);
    }

    getOnKeyListener(): ApiArray<number> {
        return new ApiArray<number>(callNum(2031, this.handle, []), 'none', null);
    }

    getOnLoadListener(): ApiArray<number> {
        return new ApiArray<number>(callNum(2032, this.handle, []), 'none', null);
    }

    getOnOpListener(): ApiArray<number> {
        return new ApiArray<number>(callNum(2033, this.handle, []), 'none', null);
    }

    getOnVarTransmitListener(): ApiArray<number> {
        return new ApiArray<number>(callNum(2034, this.handle, []), 'none', null);
    }

    getOpacity(): number {
        return callNum(2035, this.handle, []);
    }

    getOriginalHeight(): number {
        return callNum(2036, this.handle, []);
    }

    getOriginalWidth(): number {
        return callNum(2037, this.handle, []);
    }

    getOriginalX(): number {
        return callNum(2038, this.handle, []);
    }

    getOriginalY(): number {
        return callNum(2039, this.handle, []);
    }

    getParent(): Widget | null {
        return wrap(2040, this.handle, [], Widget);
    }

    getParentId(): number {
        return callNum(2041, this.handle, []);
    }

    getRelativeX(): number {
        return callNum(2042, this.handle, []);
    }

    getRelativeY(): number {
        return callNum(2043, this.handle, []);
    }

    getRotationX(): number {
        return callNum(2044, this.handle, []);
    }

    getRotationY(): number {
        return callNum(2045, this.handle, []);
    }

    getRotationZ(): number {
        return callNum(2046, this.handle, []);
    }

    getScrollHeight(): number {
        return callNum(2047, this.handle, []);
    }

    getScrollWidth(): number {
        return callNum(2048, this.handle, []);
    }

    getScrollX(): number {
        return callNum(2049, this.handle, []);
    }

    getScrollY(): number {
        return callNum(2050, this.handle, []);
    }

    getSpriteId(): number {
        return callNum(2051, this.handle, []);
    }

    getSpriteTiling(): boolean {
        return callNum(2052, this.handle, []) !== 0;
    }

    getStaticChildren(): ApiArray<Widget | null> {
        return new ApiArray<Widget | null>(callNum(2053, this.handle, []), 'handle', Widget);
    }

    getSubOps(): ApiArray<number> {
        return new ApiArray<number>(callNum(2054, this.handle, []), 'none', null);
    }

    getTargetPriority(): number {
        return callNum(2055, this.handle, []);
    }

    getTargetVerb(): string | null {
        return callStr(2056, this.handle, []);
    }

    getText(): string | null {
        return callStr(2057, this.handle, []);
    }

    getTextColor(): number {
        return callNum(2058, this.handle, []);
    }

    getTextShadowed(): boolean {
        return callNum(2059, this.handle, []) !== 0;
    }

    getType(): number {
        return callNum(2060, this.handle, []);
    }

    getVarTransmitTrigger(): ApiArray<number> {
        return new ApiArray<number>(callNum(2061, this.handle, []), 'num', null);
    }

    getWidth(): number {
        return callNum(2062, this.handle, []);
    }

    getWidthMode(): number {
        return callNum(2063, this.handle, []);
    }

    getXPositionMode(): number {
        return callNum(2064, this.handle, []);
    }

    getXTextAlignment(): number {
        return callNum(2065, this.handle, []);
    }

    getYPositionMode(): number {
        return callNum(2066, this.handle, []);
    }

    getYTextAlignment(): number {
        return callNum(2067, this.handle, []);
    }

    hasListener(): boolean {
        return callNum(2068, this.handle, []) !== 0;
    }

    isFilled(): boolean {
        return callNum(2069, this.handle, []) !== 0;
    }

    isFlippedHorizontally(): boolean {
        return callNum(2070, this.handle, []) !== 0;
    }

    isFlippedVertically(): boolean {
        return callNum(2071, this.handle, []) !== 0;
    }

    isHidden(): boolean {
        return callNum(2072, this.handle, []) !== 0;
    }

    isIf3(): boolean {
        return callNum(2073, this.handle, []) !== 0;
    }

    isSelfHidden(): boolean {
        return callNum(2074, this.handle, []) !== 0;
    }

    revalidate(): void {
        callVoid(2075, this.handle, []);
    }

    revalidateScroll(): void {
        callVoid(2076, this.handle, []);
    }

    setAction(a0: number, a1: string): void {
        callStrArg(1, a1);
        callVoid(2077, this.handle, [a0, 0]);
    }

    setAnimationId(a0: number): Widget | null {
        return wrap(2078, this.handle, [a0], Widget);
    }

    setBorderType(a0: number): void {
        callVoid(2079, this.handle, [a0]);
    }

    setClickMask(a0: number): Widget | null {
        return wrap(2080, this.handle, [a0], Widget);
    }

    setContentType(a0: number): Widget | null {
        return wrap(2081, this.handle, [a0], Widget);
    }

    setDragDeadTime(a0: number): void {
        callVoid(2082, this.handle, [a0]);
    }

    setDragDeadZone(a0: number): void {
        callVoid(2083, this.handle, [a0]);
    }

    setDragParent(a0: ApiObject | null): Widget | null {
        return wrap(2084, this.handle, [(a0 ? a0.handle : -1)], Widget);
    }

    setFilled(a0: boolean): Widget | null {
        return wrap(2085, this.handle, [(a0 ? 1 : 0)], Widget);
    }

    setFlippedHorizontally(a0: boolean): void {
        callVoid(2086, this.handle, [(a0 ? 1 : 0)]);
    }

    setFlippedVertically(a0: boolean): void {
        callVoid(2087, this.handle, [(a0 ? 1 : 0)]);
    }

    setFontId(a0: number): Widget | null {
        return wrap(2088, this.handle, [a0], Widget);
    }

    setForcedPosition(a0: number, a1: number): void {
        callVoid(2089, this.handle, [a0, a1]);
    }

    setHasListener(a0: boolean): Widget | null {
        return wrap(2090, this.handle, [(a0 ? 1 : 0)], Widget);
    }

    setHeight(a0: number): void {
        callVoid(2091, this.handle, [a0]);
    }

    setHeightMode(a0: number): Widget | null {
        return wrap(2092, this.handle, [a0], Widget);
    }

    setHidden(a0: boolean): Widget | null {
        return wrap(2093, this.handle, [(a0 ? 1 : 0)], Widget);
    }

    setItemId(a0: number): Widget | null {
        return wrap(2094, this.handle, [a0], Widget);
    }

    setItemQuantity(a0: number): Widget | null {
        return wrap(2095, this.handle, [a0], Widget);
    }

    setItemQuantityMode(a0: number): Widget | null {
        return wrap(2096, this.handle, [a0], Widget);
    }

    setLineHeight(a0: number): Widget | null {
        return wrap(2097, this.handle, [a0], Widget);
    }

    setModelId(a0: number): Widget | null {
        return wrap(2098, this.handle, [a0], Widget);
    }

    setModelType(a0: number): Widget | null {
        return wrap(2099, this.handle, [a0], Widget);
    }

    setModelZoom(a0: number): Widget | null {
        return wrap(2100, this.handle, [a0], Widget);
    }

    setName(a0: string): Widget | null {
        callStrArg(0, a0);
        return wrap(2101, this.handle, [0], Widget);
    }

    setNoClickThrough(a0: boolean): void {
        callVoid(2102, this.handle, [(a0 ? 1 : 0)]);
    }

    setNoScrollThrough(a0: boolean): void {
        callVoid(2103, this.handle, [(a0 ? 1 : 0)]);
    }

    setOpacity(a0: number): Widget | null {
        return wrap(2104, this.handle, [a0], Widget);
    }

    setOriginalHeight(a0: number): Widget | null {
        return wrap(2105, this.handle, [a0], Widget);
    }

    setOriginalWidth(a0: number): Widget | null {
        return wrap(2106, this.handle, [a0], Widget);
    }

    setOriginalX(a0: number): Widget | null {
        return wrap(2107, this.handle, [a0], Widget);
    }

    setOriginalY(a0: number): Widget | null {
        return wrap(2108, this.handle, [a0], Widget);
    }

    setPos(a0: number, a1: number): Widget | null {
        return wrap(2109, this.handle, [a0, a1], Widget);
    }

    setPos$int_int_int_int(a0: number, a1: number, a2: number, a3: number): Widget | null {
        return wrap(2110, this.handle, [a0, a1, a2, a3], Widget);
    }

    setRelativeX(a0: number): void {
        callVoid(2111, this.handle, [a0]);
    }

    setRelativeY(a0: number): void {
        callVoid(2112, this.handle, [a0]);
    }

    setRotationX(a0: number): Widget | null {
        return wrap(2113, this.handle, [a0], Widget);
    }

    setRotationY(a0: number): Widget | null {
        return wrap(2114, this.handle, [a0], Widget);
    }

    setRotationZ(a0: number): Widget | null {
        return wrap(2115, this.handle, [a0], Widget);
    }

    setScrollHeight(a0: number): Widget | null {
        return wrap(2116, this.handle, [a0], Widget);
    }

    setScrollWidth(a0: number): Widget | null {
        return wrap(2117, this.handle, [a0], Widget);
    }

    setScrollX(a0: number): Widget | null {
        return wrap(2118, this.handle, [a0], Widget);
    }

    setScrollY(a0: number): Widget | null {
        return wrap(2119, this.handle, [a0], Widget);
    }

    setSize(a0: number, a1: number): Widget | null {
        return wrap(2120, this.handle, [a0, a1], Widget);
    }

    setSize$int_int_int_int(a0: number, a1: number, a2: number, a3: number): Widget | null {
        return wrap(2121, this.handle, [a0, a1, a2, a3], Widget);
    }

    setSpriteId(a0: number): Widget | null {
        return wrap(2122, this.handle, [a0], Widget);
    }

    setSpriteTiling(a0: boolean): Widget | null {
        return wrap(2123, this.handle, [(a0 ? 1 : 0)], Widget);
    }

    setSubOp(a0: number, a1: number, a2: string): void {
        callStrArg(2, a2);
        callVoid(2124, this.handle, [a0, a1, 0]);
    }

    setTargetPriority(a0: number): void {
        callVoid(2125, this.handle, [a0]);
    }

    setTargetVerb(a0: string): void {
        callStrArg(0, a0);
        callVoid(2126, this.handle, [0]);
    }

    setText(a0: string): Widget | null {
        callStrArg(0, a0);
        return wrap(2127, this.handle, [0], Widget);
    }

    setTextColor(a0: number): Widget | null {
        return wrap(2128, this.handle, [a0], Widget);
    }

    setTextShadowed(a0: boolean): Widget | null {
        return wrap(2129, this.handle, [(a0 ? 1 : 0)], Widget);
    }

    setType(a0: number): void {
        callVoid(2130, this.handle, [a0]);
    }

    setWidth(a0: number): void {
        callVoid(2131, this.handle, [a0]);
    }

    setWidthMode(a0: number): Widget | null {
        return wrap(2132, this.handle, [a0], Widget);
    }

    setXPositionMode(a0: number): Widget | null {
        return wrap(2133, this.handle, [a0], Widget);
    }

    setXTextAlignment(a0: number): Widget | null {
        return wrap(2134, this.handle, [a0], Widget);
    }

    setYPositionMode(a0: number): Widget | null {
        return wrap(2135, this.handle, [a0], Widget);
    }

    setYTextAlignment(a0: number): Widget | null {
        return wrap(2136, this.handle, [a0], Widget);
    }

}
