// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, wrap } from './runtime';
import { Node } from './Node';

export class WidgetNode extends ApiObject {
    getHash(): number {
        return callNum(1466, this.handle, []);
    }

    getId(): number {
        return callNum(1467, this.handle, []);
    }

    getModalMode(): number {
        return callNum(1468, this.handle, []);
    }

    getNext(): Node | null {
        return wrap(1469, this.handle, [], Node);
    }

    getPrevious(): Node | null {
        return wrap(1470, this.handle, [], Node);
    }

}
