// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class WidgetClosed extends ApiObject {
    getGroupId(): number {
        return callNum(1933, this.handle, []);
    }

    getModalMode(): number {
        return callNum(1934, this.handle, []);
    }

    hashCode(): number {
        return callNum(1935, this.handle, []);
    }

    isUnload(): boolean {
        return callNum(1936, this.handle, []) !== 0;
    }

    toString(): string | null {
        return callStr(1937, this.handle, []);
    }

}
