// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { Point } from './Point';
import { Widget } from './Widget';

export class WidgetItem extends ApiObject {
    getCanvasLocation(): Point | null {
        return wrap(2152, this.handle, [], Point);
    }

    getId(): number {
        return callNum(2153, this.handle, []);
    }

    getQuantity(): number {
        return callNum(2154, this.handle, []);
    }

    getWidget(): Widget | null {
        return wrap(2155, this.handle, [], Widget);
    }

    toString(): string | null {
        return callStr(2156, this.handle, []);
    }

}
