// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class WidgetInfo extends ApiObject {
    getChildId(): number {
        return callNum(2142, this.handle, []);
    }

    getGroupId(): number {
        return callNum(2143, this.handle, []);
    }

    getId(): number {
        return callNum(2144, this.handle, []);
    }

    getPackedId(): number {
        return callNum(2145, this.handle, []);
    }

    hashCode(): number {
        return callNum(2146, this.handle, []);
    }

    name(): string | null {
        return callStr(2147, this.handle, []);
    }

    ordinal(): number {
        return callNum(2148, this.handle, []);
    }

    toString(): string | null {
        return callStr(2149, this.handle, []);
    }

}
