// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum } from './runtime';

export class WorldMapRenderer extends ApiObject {
    getMapRegions(): ApiArray<number> {
        return new ApiArray<number>(callNum(2168, this.handle, []), 'none', null);
    }

    isLoaded(): boolean {
        return callNum(2169, this.handle, []) !== 0;
    }

}
