// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { WorldView } from './WorldView';

export class WorldViewLoaded extends ApiObject {
    getWorldView(): WorldView | null {
        return wrap(1951, this.handle, [], WorldView);
    }

    hashCode(): number {
        return callNum(1952, this.handle, []);
    }

    toString(): string | null {
        return callStr(1953, this.handle, []);
    }

}
