// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { WorldView } from './WorldView';

export class WorldViewUnloaded extends ApiObject {
    getWorldView(): WorldView | null {
        return wrap(1956, this.handle, [], WorldView);
    }

    hashCode(): number {
        return callNum(1957, this.handle, []);
    }

    toString(): string | null {
        return callStr(1958, this.handle, []);
    }

}
