// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiArray, ApiObject, callNum, callStr } from './runtime';
import { World } from './World';

export class WorldListLoad extends ApiObject {
    getWorlds(): ApiArray<World | null> {
        return new ApiArray<World | null>(callNum(1950, this.handle, []), 'handle', World);
    }

    hashCode(): number {
        return callNum(1951, this.handle, []);
    }

    toString(): string | null {
        return callStr(1952, this.handle, []);
    }

}
