// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, wrap } from './runtime';
import { WorldPoint } from './WorldPoint';

export class WorldMapIcon extends ApiObject {
    getCoordinate(): WorldPoint | null {
        return wrap(2164, this.handle, [], WorldPoint);
    }

    getType(): number {
        return callNum(2165, this.handle, []);
    }

}
