// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { WorldEntity } from './WorldEntity';

export class WorldEntitySpawned extends ApiObject {
    getWorldEntity(): WorldEntity | null {
        return wrap(1947, this.handle, [], WorldEntity);
    }

    hashCode(): number {
        return callNum(1948, this.handle, []);
    }

    toString(): string | null {
        return callStr(1949, this.handle, []);
    }

}
