// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr } from './runtime';

export class WorldType extends ApiObject {
    hashCode(): number {
        return callNum(1500, this.handle, []);
    }

    name(): string | null {
        return callStr(1501, this.handle, []);
    }

    ordinal(): number {
        return callNum(1502, this.handle, []);
    }

    toString(): string | null {
        return callStr(1503, this.handle, []);
    }

}
