// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum } from './runtime';

export class WorldMapData extends ApiObject {
    surfaceContainsPosition(a0: number, a1: number): boolean {
        return callNum(2163, this.handle, [a0, a1]) !== 0;
    }

}
