// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callStr, wrap } from './runtime';
import { WorldEntity } from './WorldEntity';

export class WorldEntityDespawned extends ApiObject {
    getWorldEntity(): WorldEntity | null {
        return wrap(1944, this.handle, [], WorldEntity);
    }

    hashCode(): number {
        return callNum(1945, this.handle, []);
    }

    toString(): string | null {
        return callStr(1946, this.handle, []);
    }

}
