// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, wrap } from './runtime';
import { WorldPoint } from './WorldPoint';

export class WorldArea extends ApiObject {
    canTravelInDirection(a0: ApiObject | null, a1: number, a2: number): boolean {
        return callNum(1570, this.handle, [(a0 ? a0.handle : -1), a1, a2]) !== 0;
    }

    contains(a0: ApiObject | null): boolean {
        return callNum(1571, this.handle, [(a0 ? a0.handle : -1)]) !== 0;
    }

    contains2D(a0: ApiObject | null): boolean {
        return callNum(1572, this.handle, [(a0 ? a0.handle : -1)]) !== 0;
    }

    distanceTo(a0: ApiObject | null): number {
        return callNum(1573, this.handle, [(a0 ? a0.handle : -1)]);
    }

    distanceTo$WorldPoint(a0: ApiObject | null): number {
        return callNum(1574, this.handle, [(a0 ? a0.handle : -1)]);
    }

    distanceTo2D(a0: ApiObject | null): number {
        return callNum(1575, this.handle, [(a0 ? a0.handle : -1)]);
    }

    distanceTo2D$WorldPoint(a0: ApiObject | null): number {
        return callNum(1576, this.handle, [(a0 ? a0.handle : -1)]);
    }

    getHeight(): number {
        return callNum(1577, this.handle, []);
    }

    getPlane(): number {
        return callNum(1578, this.handle, []);
    }

    getWidth(): number {
        return callNum(1579, this.handle, []);
    }

    getX(): number {
        return callNum(1580, this.handle, []);
    }

    getY(): number {
        return callNum(1581, this.handle, []);
    }

    hasLineOfSightTo(a0: ApiObject | null, a1: ApiObject | null): boolean {
        return callNum(1582, this.handle, [(a0 ? a0.handle : -1), (a1 ? a1.handle : -1)]) !== 0;
    }

    hasLineOfSightTo$WorldView_WorldPoint(a0: ApiObject | null, a1: ApiObject | null): boolean {
        return callNum(1583, this.handle, [(a0 ? a0.handle : -1), (a1 ? a1.handle : -1)]) !== 0;
    }

    intersectsWith(a0: ApiObject | null): boolean {
        return callNum(1584, this.handle, [(a0 ? a0.handle : -1)]) !== 0;
    }

    isInMeleeDistance(a0: ApiObject | null): boolean {
        return callNum(1585, this.handle, [(a0 ? a0.handle : -1)]) !== 0;
    }

    isInMeleeDistance$WorldPoint(a0: ApiObject | null): boolean {
        return callNum(1586, this.handle, [(a0 ? a0.handle : -1)]) !== 0;
    }

    toWorldPoint(): WorldPoint | null {
        return wrap(1587, this.handle, [], WorldPoint);
    }

}
