// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, callVoid, wrap } from './runtime';
import { Point } from './Point';
import { WorldMapData } from './WorldMapData';
import { WorldMapRenderer } from './WorldMapRenderer';

export class WorldMap extends ApiObject {
    getWorldMapData(): WorldMapData | null {
        return wrap(2159, this.handle, [], WorldMapData);
    }

    getWorldMapPosition(): Point | null {
        return wrap(2160, this.handle, [], Point);
    }

    getWorldMapRenderer(): WorldMapRenderer | null {
        return wrap(2161, this.handle, [], WorldMapRenderer);
    }

    getWorldMapZoom(): number {
        return callNum(2162, this.handle, []);
    }

    initializeWorldMap(a0: ApiObject | null): void {
        callVoid(2163, this.handle, [(a0 ? a0.handle : -1)]);
    }

    setWorldMapPositionTarget(a0: ApiObject | null): void {
        callVoid(2164, this.handle, [(a0 ? a0.handle : -1)]);
    }

}
