// Generated by the :web:web-client generateApiBridge task. Do not edit.
import { ApiObject, callNum, wrap } from './runtime';
import { LocalPoint } from './LocalPoint';
import { WorldEntityConfig } from './WorldEntityConfig';
import { WorldView } from './WorldView';

export class WorldEntity extends ApiObject {
    getCameraFocus(): LocalPoint | null {
        return wrap(1485, this.handle, [], LocalPoint);
    }

    getConfig(): WorldEntityConfig | null {
        return wrap(1486, this.handle, [], WorldEntityConfig);
    }

    getLocalLocation(): LocalPoint | null {
        return wrap(1487, this.handle, [], LocalPoint);
    }

    getOrientation(): number {
        return callNum(1488, this.handle, []);
    }

    getOwnerType(): number {
        return callNum(1489, this.handle, []);
    }

    getTargetLocation(): LocalPoint | null {
        return wrap(1490, this.handle, [], LocalPoint);
    }

    getTargetOrientation(): number {
        return callNum(1491, this.handle, []);
    }

    getWorldView(): WorldView | null {
        return wrap(1492, this.handle, [], WorldView);
    }

    isHiddenForOverlap(): boolean {
        return callNum(1493, this.handle, []) !== 0;
    }

    transformToMainWorld(a0: ApiObject | null): LocalPoint | null {
        return wrap(1494, this.handle, [(a0 ? a0.handle : -1)], LocalPoint);
    }

}
